jupyter-server/enterprise_gateway

- README.md
> Update README - fix typo

- docs/source/devinstall.md
- etc/kernel-launchers/scala/toree-launcher/project/build.properties
- etc/kernel-launchers/scala/toree-launcher/project/plugins.sbt
Small fix. Related to issue #225
> Change sbt.version of Toree Launcher to 1.0.3

- etc/docker/yarn-spark/Dockerfile
> Update Java distribution in Docker images

- enterprise_gateway/client/gateway_client.py
- enterprise_gateway/itests/test_python_kernel.py
- enterprise_gateway/itests/test_r_kernel.py
- enterprise_gateway/itests/test_scala_kernel.py
Refactor 'gateway client' to client package as an experimental
feature.
> Refactor client to regular source package

- enterprise_gateway/client/gateway_client.py
> remove new line on the join

- enterprise_gateway/client/gateway_client.py
- enterprise_gateway/enterprisegatewayapp.py
- setup.py
In order to be able to import the package from another application, it needs to be exposed.
> Updates to expose Gateway Client (EXPERIMENTAL FEATURE)

- etc/docker/yarn-spark/Dockerfile
includes minor update to comment with correct spark version
> Update JDK link for yarn-spark docker image

- docs/source/troubleshooting.md
Added scenarios for what kind of information should be provided when
opening new issues and how to troubleshoot immediately following
installation.
> Update troubleshooting page with more general scenarios

- Makefile
- docs/source/getting-started-client-mode.md
- docs/source/getting-started-cluster-mode.md
- docs/source/getting-started-kernels.md
- docs/source/getting-started.md
- docs/source/roadmap.md
- enterprise_gateway/__init__.py
- enterprise_gateway/_version.py
- etc/Makefile
- etc/docker/enterprise-gateway-demo/Dockerfile
- etc/kubernetes/enterprise-gateway.yaml
Multiple commits to enable automating the release while properly updating:
- docker tags
- documentation version
- package version
> Release automation preparation enhancements

- Makefile
- README.md
- docs/source/getting-started-kernels.md
- etc/Makefile
- etc/docker/nb2kg/README.md
- etc/docker/yarn-spark/Dockerfile
- etc/docker/yarn-spark/README.md
- etc/kernel-launchers/scala/toree-launcher/build.sbt
- etc/kernel-launchers/scala/toree-launcher/project/project/build.properties
Minor enhancements for review:
- Enhance make clean
- Fix links to jupyter-incubator
- Move to Toree 0.3.0-incubator
- Add scala launcher build.properties
> Minor enhancements

- docs/source/getting-started-kubernetes.md
- etc/docker/demo-base/Dockerfile
- etc/docker/enterprise-gateway-demo/Dockerfile
- etc/docker/enterprise-gateway-demo/README.md
- etc/docker/enterprise-gateway-demo/bootstrap-enterprise-gateway.sh
- etc/docker/enterprise-gateway/Dockerfile
- etc/docker/enterprise-gateway/bootstrap-enterprise-gateway.sh
- etc/docker/kernel-py/Dockerfile
- etc/docker/kernel-r/Dockerfile
- etc/docker/kernel-scala/Dockerfile
- etc/docker/kernel-spark-py/Dockerfile
- etc/docker/kernel-spark-r/Dockerfile
- etc/docker/kernel-tf-gpu-py/Dockerfile
- etc/docker/kernel-tf-py/Dockerfile
- etc/docker/nb2kg/Dockerfile
- etc/kernel-launchers/docker/scripts/launch_docker.py
- etc/kernel-launchers/kubernetes/scripts/kernel-pod.yaml
Update the location of various bootstrap and startup scripts to be
more in line with the Jupyter community as well as default user to
"jovyan"
Fixes #480
> Update image startup script locations

- etc/kernel-launchers/scala/toree-launcher/src/main/scala/launcher/ToreeLauncher.scala
In certain spark environments and dependency issue can rise such that
the play framework JSON code that uses backslash `\` to access field
values raises a NoSuchMethodError.  This issue can be avoided by using
more primitive methods for accessing field values and that's what this
change does.
> Avoid use of backslash operator when working with JSON

- etc/kernel-launchers/scala/toree-launcher/src/main/scala/launcher/ToreeLauncher.scala
This PR is equivalent to #510 but relative to the master branch.
> Avoid use of backslash operator when working with JSON (master)

- requirements.yml
Syncronyze conda requirements with setup.py
> Update conda requirements definition

- etc/docker/enterprise-gateway/Dockerfile
This fixes build error due to missing packages.
Closes #581
Signed-off-by: Eunsoo Park <esevan.park@gmail.com>
If  there's any missing point in my build process, please close this PR.
> Install additional packages (linux-headers, zeromq-dev)

- enterprise_gateway/services/processproxies/k8s.py
When EG creates the kernel pod's namespace (default behavior), restarts
would fail because the restart encouters an existing (but terminating)
namespace during the start portion of the restart (with the shutdown portion
having triggered the namespace's termination).  This change only deletes
the kernel pod during shutdowns associated with restarts, then tolerates
the namespace's existence after creation.  Note we still attempt the
namespace creation in case it was deleted outside of EG and a kernel
restart was attempted to rectify the situation.  This results in restart
behaviors identical to that if the user brought their own namespace.
Fixes #578
> Fix k8s kernel restarts when EG creates kernel namespace

- etc/docker/enterprise-gateway/Dockerfile
- etc/docker/enterprise-gateway/README.md
- etc/docker/enterprise-gateway/ssh_config
- Install Apache Spark with req. symlinks
> Rebase EG docker image to use jupyter/minimal-notebook

- .travis.yml
- Makefile
- enterprise_gateway/client/gateway_client.py
- enterprise_gateway/enterprisegatewayapp.py
- enterprise_gateway/itests/test_authorization.py
- enterprise_gateway/itests/test_base.py
- enterprise_gateway/services/kernels/remotemanager.py
- enterprise_gateway/services/processproxies/conductor.py
- enterprise_gateway/services/processproxies/docker_swarm.py
- enterprise_gateway/services/processproxies/k8s.py
- enterprise_gateway/services/processproxies/processproxy.py
- enterprise_gateway/services/processproxies/yarn.py
- enterprise_gateway/services/sessions/kernelsessionmanager.py
- enterprise_gateway/tests/notebook_http/cell/test_parser.py
- enterprise_gateway/tests/notebook_http/swagger/test_builders.py
- enterprise_gateway/tests/notebook_http/swagger/test_parser.py
- enterprise_gateway/tests/notebook_http/test_request_utils.py
- enterprise_gateway/tests/test_enterprise_gateway.py
- enterprise_gateway/tests/test_gatewayapp.py
- enterprise_gateway/tests/test_jupyter_websocket.py
- enterprise_gateway/tests/test_mixins.py
- enterprise_gateway/tests/test_notebook_http.py
- requirements.yml
Use Flake8 to check/enforce code style conformance
> Add code style/lint make task and fix PEP8 failures 

- enterprise_gateway/services/processproxies/yarn.py
On YARN systems, there's a tendency for the shutdown times to exceed the default wait time of 5 seconds.  Rather than require customers that need to use YARN to set another command-line option, this change will increase the timeout only when `YarnClusterProcessProxy` instances are in play.  The increase only occurs if the current value is less than the desired value.   This value defaults to 15 seconds and can be adjusted via env `EG_YARN_SHUTDOWN_WAIT_TIME`.
If debug is enabled, the following will be logged at kernel startup and when adjustment is performed:
```
[D 2019-03-15 14:33:17.943 EnterpriseGatewayApp] YarnClusterProcessProxy shutdown wait time adjusted to 15.0 seconds.
```
> Increase shutdown wait time for YARN kernels

- docs/source/docker.md
- etc/docker/kernel-tf-gpu-py/Dockerfile
Add commands to install OS dependencies and update
docs for custom kernel image.
Fixes #622
Signed-off-by: Eunsoo Park <esevan.park@gmail.com>
> Change kernel-tf-gpu-py image

- docs/source/kernel-kubernetes.md
> Fix typos in helm docs: kernelspecs_image should kernelspecs.image

- docs/source/getting-started.md
Discovered during 2.0 inspection (#723) that we haven't updated the NB2KG material to include mention of using Notebook 6.0 - since it's now built in.
> Add notebook 6 content to NB2KG section

- etc/kernel-launchers/python/scripts/launch_ipykernel.py
- Use `ExceptionThread` instead of `Thread` to handle the exception when initializing spark session.
**Before: Thread exception was hidden**
**After: Show more detail**
> Catch thread exception in kernel-spark-py

- docs/source/kernel-kubernetes.md
- etc/kernel-launchers/kubernetes/scripts/kernel-pod.yaml.j2
As talked about in issue #749 there was a need to document the conditional and unconditional volumeMounts and volumes. 
This should be documented?
> Restructure the kernel-pod.yaml.j2 template

- etc/kubernetes/enterprise-gateway.yaml
Modify apiVersion to correspond to kubernetes 1.16
**Commit Formatting**
Please follow the **[seven rules of a great commit message](https://chris.beams.io/posts/git-commit/)**
- Separate subject from body with a blank line
- Limit the subject line to 50 characters
- Capitalize the first word of the subject line
- Do not end the subject line with a period
- Use the imperative mood in the subject line
- Wrap the body at 72 characters
- Use the body to explain what and why vs. how
**Closing issues**
- Put `Closes #XXXX`in your commit comment to auto-close this PR when merged.
- Put `Fixes  #XXXX`in your commit comment to auto-close the issue that your PR fixes (if such).
> Modify apiVersion to correspond to kubernetes 1.16

- enterprise_gateway/services/processproxies/yarn.py
This addresses issues relative to interactions with the yarn-api-client.
It introduces `last_known_state` so that cases where the YARN resource
manager has access issues during EG's polling interval (every 3 seconds)
the last known state will be used.  Previously, EG would essentially
crash when referencing a null response (which has also been addressed).
With these changes, EG may be able to continue if the kernel is still
communicating, even though YARN's RM is not.
This PR is a prerequisite to troubleshooting #762.
> Fix YARN API error handling

- etc/docker/demo-base/Dockerfile
- etc/docker/enterprise-gateway-demo/Dockerfile
- etc/docker/enterprise-gateway/Dockerfile
- Update apache link to follow redirect due to new location of
binaries and update CRAN mirror following closure of berkeley
mirror
- Minor change to tmp dir in dockerfile to satisfy docker build
syntax
**Commit Formatting**
Please follow the **[seven rules of a great commit message](https://chris.beams.io/posts/git-commit/)**
- Separate subject from body with a blank line
- Limit the subject line to 50 characters
- Capitalize the first word of the subject line
- Do not end the subject line with a period
- Use the imperative mood in the subject line
- Wrap the body at 72 characters
- Use the body to explain what and why vs. how
**Closing issues**
- Put `Closes #XXXX`in your commit comment to auto-close this PR when merged.
- Put `Fixes  #XXXX`in your commit comment to auto-close the issue …
> Update links in Dockerfiles

- enterprise_gateway/services/kernels/remotemanager.py
Update cleanup method signature to match jupyter_client pkg
- https://github.com/jupyter/jupyter_client/pull/548#pullrequestreview-417826199
> [Bugfix] Update cleanup method signature

- etc/docker/docker-compose.yml
- etc/kernel-launchers/docker/scripts/launch_docker.py
- Update version in compose yaml to 3.5
- Update network name to use swarm default, allow env override
- Fix container startup args for regular docker
> Fix docker integrations

- requirements.yml
**Commit Formatting**
Please follow the **[seven rules of a great commit message](https://chris.beams.io/posts/git-commit/)**
- Separate subject from body with a blank line
- Limit the subject line to 50 characters
- Capitalize the first word of the subject line
- Do not end the subject line with a period
- Use the imperative mood in the subject line
- Wrap the body at 72 characters
- Use the body to explain what and why vs. how
**Closing issues**
- Put `Closes #XXXX`in your commit comment to auto-close this PR when merged.
- Put `Fixes  #XXXX`in your commit comment to auto-close the issue that your PR fixes (if such).
> Properly handle notebook rc during make env

- enterprise_gateway/enterprisegatewayapp.py
- enterprise_gateway/mixins.py
- enterprise_gateway/tests/test_gatewayapp.py
Fixes [Issue 339](https://github.com/jupyter/kernel_gateway/issues/339)
> make ssl_version as EG config option

- docs/source/kernel-kubernetes.md
- etc/kernel-launchers/kubernetes/scripts/kernel-pod.yaml.j2
- Add `{{ kernel_cpus }}`, `{{ kernel_memory }}`, `{{ kernel_gpus }}`, `{{ kernel_cpus_limit }}`, `{{ kernel_memory_limit }}` and `{{ kernel_gpus_limit }}` into template with conditional
- `{{ kernel_cpus }}` - CPU Request 
- `{{ kernel_memory }}` - Memory Request 
- `{{ kernel_gpus }}` - GPU Request 
- `{{ kernel_cpus_limit }}` - CPU Limit 
- `{{ kernel_memory_limit }}` - Memory Limit 
- `{{ kernel_gpus_limit }}`  - GPU Limit 
Unit-based on official Kubernetes documentation https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
Ref #770 #775
> Add resource limit into K8s kernel pod template

- enterprise_gateway/base/handlers.py
- enterprise_gateway/client/gateway_client.py
- enterprise_gateway/enterprisegatewayapp.py
- enterprise_gateway/itests/test_authorization.py
- enterprise_gateway/itests/test_python_kernel.py
- enterprise_gateway/itests/test_r_kernel.py
- enterprise_gateway/itests/test_scala_kernel.py
- enterprise_gateway/mixins.py
- enterprise_gateway/services/kernels/remotemanager.py
- enterprise_gateway/services/kernelspecs/handlers.py
- enterprise_gateway/services/processproxies/conductor.py
- enterprise_gateway/services/processproxies/container.py
- enterprise_gateway/services/processproxies/distributed.py
- enterprise_gateway/services/processproxies/docker_swarm.py
- enterprise_gateway/services/processproxies/k8s.py
- enterprise_gateway/services/processproxies/processproxy.py
- enterprise_gateway/services/processproxies/yarn.py
- enterprise_gateway/services/sessions/kernelsessionmanager.py
- enterprise_gateway/tests/test_enterprise_gateway.py
- enterprise_gateway/tests/test_handlers.py
- setup.cfg
> Fixes flake8 lint violations

- docs/source/docker.md
- etc/docker/kernel-tf-gpu-py/Dockerfile
- etc/docker/kernel-tf-py/Dockerfile
> Update TF kernelspecs to Tensorflow 2.4.0 release

- Makefile
- etc/Makefile
- etc/docker/kernel-tf-gpu-py/Dockerfile
> Fix docker image makefile tasks

- etc/kernel-launchers/R/scripts/gateway_listener.py
- etc/kernel-launchers/python/scripts/launch_ipykernel.py
I modified the logic to convert EG_LOG_LEVEL to int, because of Docker support.
Fixes #962
> Modify the logic that converts EG_LOG_LEVEL to int

- enterprise_gateway/services/kernelspecs/handlers.py
mildly [unidiomatic](https://docs.python.org/3/glossary.html#term-eafp)
> use idiomatic key checking

- etc/docker/kernel-image-puller/kernel_image_puller.py
- etc/docker/kernel-image-puller/requirements.txt
- etc/kubernetes/enterprise-gateway.yaml
#992 
i haven't find out a pull image api in containerd gRPC. so just failover first
> make KIP sleep when container runtime is not docker

- enterprise_gateway/services/processproxies/distributed.py
> Fix issue when log file got rewritten on kernel's restart

- enterprise_gateway/services/processproxies/yarn.py
If anonymous access is disallowed on the Hadoop YARN cluster,  and kerberos is not enabled, requests against the YARN API will fail with a `401` indicating authentication is required.  This change uses the newly added `SimpleAuth` from the yarn-api-client package to satisfy such configurations.  Since the specified username is not required to be an actual user, this fits in nicely with the notion of `KERNEL_USERNAME`, so we will set the `SimpleAuth`'s username to whatever we have deemed to be the kernel username at the time of the launch.  This resulted in a repositioning of the establishment of the resource manager connection to the actual kernel launch, rather than the `YarnClusterProcessProxy` constructor.
The implementation tolerates older versions of yarn-api-client since allowing …
> Add support for YARN API non-anonymous access

- docs/source/contributors/devinstall.md
specificaaation -> specification
> fix small typo in developer docs

- enterprise_gateway/services/kernels/remotemanager.py
- enterprise_gateway/services/processproxies/processproxy.py
- enterprise_gateway/services/sessions/kernelsessionmanager.py
- enterprise_gateway/services/sessions/sessionmanager.py
- enterprise_gateway/tests/test_enterprise_gateway.py
cf https://github.com/jupyter/nbconvert/issues/1725
> Remove usage of ipython_genutils

- .github/workflows/build.yml
- Makefile
- enterprise_gateway/enterprisegatewayapp.py
- enterprise_gateway/tests/test_handlers.py
- pyproject.toml
- setup.py
- Use config from `jupyter_server`
- Handle warnings
> Clean up pytest handling

- Makefile
Mostly doing this to make helm pieces a little more flexible as I have helm deployed via brewer to a different location.
> Enable overriding Helm location from env var

- docs/source/operators/config-add-env.md
- docs/source/operators/config-env-debug.md
- enterprise_gateway/mixins.py
- enterprise_gateway/services/kernels/remotemanager.py
* expose tunable ZMQ_MAX_SOCKETS
* expose tunable IO_THREADS
> Add hook to modify zmq.Context

- Makefile
- etc/Makefile
- etc/docker/demo-base/Dockerfile
- etc/docker/demo-base/bootstrap-yarn-spark.sh
- etc/docker/enterprise-gateway/Dockerfile
- etc/docker/kernel-spark-py/Dockerfile
- etc/docker/kernel-spark-r/Dockerfile
- release.sh
1. change JAVA_HOME to be generic
2. use continuumio/miniconda3 as base image for demo-base to remove platform specific package
3. change make file to build multi-arch image using buildx
> multiarch image build support

- .github/workflows/build.yml
- .pre-commit-config.yaml
- Makefile
- codecov.yml
- pyproject.toml
Add coverage report config
Workflow cleanup
Add explicit python 3.11 support
> Maintenance cleanup

- etc/docker/kernel-tf-py/README.md
> Update link to tensorflow-notebook image

- Makefile
- etc/kubernetes/helm/enterprise-gateway/templates/daemonset.yaml
- etc/kubernetes/helm/enterprise-gateway/templates/deployment.yaml
- etc/kubernetes/helm/enterprise-gateway/templates/eg-serviceaccount.yaml
- etc/kubernetes/helm/enterprise-gateway/templates/ingress.yaml
- etc/kubernetes/helm/enterprise-gateway/templates/kip-serviceaccount.yaml
- etc/kubernetes/helm/enterprise-gateway/templates/service.yaml
> Enable specifying helm chart deployment namespace
