jupyter-server/enterprise_gateway

docs/source/getting-started-kernels.md

Fixed the broken link to kernelspec tar file. However, while on this
page I discovered the need for the following changes.
1. We had duplicate statements for Scala and Python sections so I moved
to the beginning section where all three kernels are referenced.
2. Both code blocks for Scala and Python instructions referenced invalid
links to 0.6 and then used referenced invalid tar files.  With the changes,
they *should* be able to cut/paste the instructions.
3. We were missing the comparable section for the iR kernel - so I added it.
Fixes #229

[HOTFIX] Fix broken link to kernelspecs tar file.

---

enterprise_gateway/itests/notebooks/Python_Client1.ipynb
enterprise_gateway/itests/notebooks/Python_Cluster1.ipynb
enterprise_gateway/itests/notebooks/R_Client1.ipynb
enterprise_gateway/itests/notebooks/R_Cluster1.ipynb
enterprise_gateway/itests/notebooks/Scala_Client1.ipynb
enterprise_gateway/itests/notebooks/Scala_Cluster1.ipynb
enterprise_gateway/itests/src/elyra_client.py
enterprise_gateway/itests/src/itest_notebook.py
enterprise_gateway/itests/src/nb_entity.py

Related to issue #30 
Currently the content of each language's notebook is not consistent with other language, and in order to make us easier to compare the testing for each kernel, I normalized those notebooks so their contents are almost the same (Except for Scala kernels since we need to test `Toree magic`).
Also, now itest supports printing each code-cell/step of each notebook so when get stuck, we could detect which code cell might be the reason.

Integration test enhancement

---

enterprise_gateway/itests/notebooks/Python_Client1.ipynb
enterprise_gateway/itests/src/elyra_client.py
enterprise_gateway/itests/src/itest_notebook.py
enterprise_gateway/itests/src/main.py
enterprise_gateway/itests/src/nb_entity.py

Related to issue #238 
Now we could do impersonation test by providing the `impersonation_username` flag with the target username, e.g. `bob`. Here is the logic:
1. For python client notebook, the newly added code cell `!whoami` would be executed
2. The first line of that code cell should contain `IMPERSONATION`, so the assert code would be returned as 3
3. If the assert code is 3, and the variable `impersonation_username` is not `None` in Python, then the output of the `!whoami` code cell would be compared with the `impersonation_username`
4. If they are the same, then it is a pass test case
Some other things to notice here:
1) It actually doesn't matter what output would be returned from the code cell of `!whoami` on the python client notebook file. The only thing matters here is if the …

First version implementation of impersonation integration test

---

etc/kernel-launchers/R/scripts/launch_IRkernel.R

Updated the R launcher script to include Kernel ID instead of "SparkR" as application name in YARN resource manager

Fix R-kernel to show kernel ID as app name in YARN RM

---

docs/source/config-options.md
docs/source/getting-started-security.md
enterprise_gateway/services/processproxies/processproxy.py

For enhanced security, the connections between the
Jupyter Enterprise Gateway and the Kernel as well as
the connection between the Enterprise Gateway and the
Kernel Launcher have been made secure by default. The
documentation has been updated as well with details
about how to turn off tunneling for troubleshooting
purposes.
Addresses #234.

Enable SSH tunneling by default

---

etc/kernelspecs/spark_R_yarn_cluster/kernel.json
etc/kernelspecs/spark_python_yarn_cluster/kernel.json
etc/kernelspecs/spark_scala_yarn_cluster/kernel.json

Spark 2.2 no longer supports SPARK_YARN_USER_ENV. This removes that deprecated ENV var in the R kernelspec and instead passes in the Yarn env via an extra --conf parameter in spark-submit.

Updated YARN cluster mode kernelspecs to use new spark conf parameter

---

enterprise_gateway/services/kernels/remotemanager.py
etc/kernel-launchers/scala/toree-launcher/src/main/scala/launcher/ToreeLauncher.scala
etc/kernelspecs/spark_scala_yarn_client/kernel.json
etc/kernelspecs/spark_scala_yarn_cluster/kernel.json

Replaced the use of environment variable TOREE_ALTERNATE_SIGINT
with a command-line option --alternate-sigint that is passed in
using __TOREE_OPTS__ in the kernel.json files. Updated the
relevant kernel.json files as well. Also, removed dead code in
remotemanager.py that was dealing with EG_ALTERNATE_SIGINT
environment variable.
Addresses issue #231.

Toree Launcher: --alternate-sigint command-line option

---

Makefile
enterprise_gateway/enterprisegatewayapp.py
etc/docker/enterprise-gateway/Dockerfile

[Notebook PR 3714](https://github.com/jupyter/notebook/pull/3714/) in 5.6.0 has code that prevents remote host access.  Since
the entire purpose of Enterprise Gateway is to allow remote host access, we need
to enable the web setting `allow_remote_access` to prevent the 403 exception.
This was discovered due to recent Travis build failures since it uses updated resources.
This led to other dependency related issues, namely in the docker image used for
testing leading to the update of the jupyter framework files in the `Dockerfile`.
Also increased the timeout for waiting for the docker image startup from 30
to 60 seconds and added the ability to override on the command line using
`PREP_TIMEOUT=n`.

Allow access from remote hosts

---

docs/source/docker.md
docs/source/getting-started-kubernetes.md
docs/source/system-architecture.md
etc/docker/kubernetes-enterprise-gateway/README.md
etc/docker/kubernetes-kernel-py/README.md
etc/docker/kubernetes-kernel-r/README.md
etc/docker/kubernetes-kernel-scala/README.md
etc/docker/kubernetes-kernel-tf-gpu-py/README.md
etc/docker/kubernetes-kernel-tf-py/README.md
etc/docker/kubernetes-spark-kernel-r/README.md

A recent change to the kubernetes build invalidated the location of the
`enterprise-gateway.yaml` file that is referenced in all of the kubernetes
image README files and online docs.  These changes correct those references.

Fix references to kubernetes yaml file

---

etc/docker/kubernetes-enterprise-gateway/Dockerfile
etc/docker/kubernetes-kernel-scala/Dockerfile

Now that Toree assembly is already part of the kernelspecs
distribution we don't need to manually add the jar into
lib folder.

Remove obsolete code that downloads Toree assembly

---

docs/source/getting-started-kernels.md

Considering we would like to enable the Scala Kernel to run on YARN Cluster and Client mode
we would have to copy the sample configuration folder **spark_scala_yarn_client** and
**spark_scala_yarn_client** to where the Jupyter kernels are installed  --> instead of ** spark_scala_yarn_cluster **  **spark_scala_yarn_client** is mentioned twice

Typo's in content change

---

etc/Makefile
etc/kernelspecs/python_tf_gpu_kubernetes/kernel.json

Fixed the image referenced in the kernel.json file to match that produced
by the build and in dockerhub.
Fixed the Makefile to include the python_tf_gpu_kubernetes directory in the
set of directories that require extension with kernel-pod.yaml and k8s
launch script.
Perform a second copy of source directories at end to allow per-kernel overrides
of files that are otherwise generic.  This would allow for, say, the python_tf_gpu
kernelspec directory to contain its own kernel-pod.yaml file that contains pod-
specific information.  Although not ideal, due to the redundancy it introduces
with the default kernel-pod.yaml file, it does allow for finer-grained customization
in a straightforward manner.
Fixes #425

Fix python_tf_gpu_kubernetes kernelspec

---

enterprise_gateway/itests/test_python_kernel.py
enterprise_gateway/services/processproxies/distributed.py
etc/docker/enterprise-gateway-demo/Dockerfile
etc/docker/yarn-spark/bootstrap-yarn-spark.sh
etc/kernelspecs/python_distributed/kernel.json

DistributedProcessProxy is now "optimized" for the case when the target
host is the local server.  In such cases, use of ssh is bypassed and
kernel management is like that of the local case with the exception that
message-based interrupts still go through the communication port (in loopback).
Another advantage is that ZMQ port creation will occur much closer to the
invocation of the kernel - thereby significantly reducing the window where
port conflicts can arise.
Added example kernelspec - python_distributed - which demonstrates how the
native python kernel could be reconfigured to work in a distributed manner.
Updated integration test to exercise the distributed python kernel similar
to how the local python kernel is tested.
Found issues with the EG and Yarn images relative to the R …

Update DistributedProcessProxy to not use ssh if host is local server

---

enterprise_gateway/services/processproxies/processproxy.py

On python 3.x systems and reported in issues #432 and #435, the existing launch
failure detection was producing the following `TypeError` exception:
```
File "/opt/anaconda3/lib/python3.6/site-packages/enterprise_gateway/services/
processproxies/processproxy.py", line 587, in detect_launch_failure
if self.local_proc and self.local_proc.poll() > 0:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```
This change checks if the result from `poll()` is None prior to checking its
value.
NOTE: This change should be added to the 1.x branch for a patch release.

Fix kernel launch failure detection

---

docs/source/config-options.md
enterprise_gateway/services/kernels/remotemanager.py
enterprise_gateway/tests/__init__.py
enterprise_gateway/tests/resources/kernels/kernel_defaults_test/kernel.json
enterprise_gateway/tests/test_jupyter_websocket.py

Prior to this change, any values in the env stanza of a kernelspec would
override values provided by the caller in the json's env section - thereby
eliminating the ability to let those values defined in the kernelspec to
be used as defaults and the user-provided values used as overrides. Following
this change any json env's prefixed with KERNEL_ or appearing in the
KG_ENV_WHITELIST or KG_PROCESS_ENV_WHITELIST will be added back into the
kernel's env after it has been seeded with values from the kernelspec.  The
only exception to this is the internally defined KERNEL_GATEWAY variable which
is set to '1' to indicate the kernel was launched by the gateway.
Added test to validate this behavior.  This test requires use of locally
defined kernelspec so I added the ability to define such …

Add ability to use kernelspec.env for default values

---

etc/Makefile

We have been retagging images with <tag>_x (typically dev_x) as
a means of retaining a copy of the previous image.  Since we have
not really found a need to rollback to the "backup" image and because
this increases disk space consumption, we will stop doing this.
Developers can clean up their dev_x tagged images via:
```
docker rmi -f `docker images |grep dev_x |awk '{print $3}'`
```

Stop tagging images with dev_x as a means of image backup

---

enterprise_gateway/enterprisegatewayapp.py

We noticed that on python 3.x python would not ignore the SIGHUP by default. We made the similar change in kernel gateway, you can see the discussion here 
https://github.com/jupyter/kernel_gateway/pull/304

Allow enterprise gateway to ignore the SIGHUP signal

---

docs/environment.yml
requirements.yml

Documentation builds were failing after Sphinx was bumped up to 1.8.0. Was unable to recreate the error locally. This PR will test to see if reverting to 1.7.9 resolves the issue.

Set Sphinx to use v1.7.9

---

requirements.yml
setup.py

kerberos issues with the new release of yarn-api-client

Set EG to use yarn-api-client dependency <0.3.0

---

docs/source/config-options.md
docs/source/getting-started-security.md
enterprise_gateway/enterprisegatewayapp.py
enterprise_gateway/services/processproxies/yarn.py
etc/docker/enterprise-gateway/Dockerfile
etc/docker/yarn-spark/Dockerfile
setup.py

Update to the YARN client API package that has now
enabled SPENEGO support and properly expose a parameter
for the user to enable/disable support for SPENEGO in
Enterprise Gateway. Also update the docker images with
kerberos library dependencies.
Closes #459

Add support to YARN endpoints protected by SPNEGO

---

docs/source/getting-started-security.md

Clarifies how/where user impersonation flags should be configured:
`EG_IMPERSONATION_ENABLED` and `YARN_ENDPOINT_SECURITY_ENABLED`

Additional clarification on user impersonation documentation

---

enterprise_gateway/enterprisegatewayapp.py

This will help us during times of support.  It would be nice to capture all the components, but we can ask for a `pip freeze` for those.
Before:
```
[I 2018-10-10 12:53:16.677 EnterpriseGatewayApp] Jupyter Enterprise Gateway at http://0.0.0.0:8888
```
After:
```
[I 2018-10-10 12:53:16.677 EnterpriseGatewayApp] Jupyter Enterprise Gateway 1.1.0 is available at http://0.0.0.0:8888
```

Add the Enterprise Gateway version stamp to the startup message.

---

Makefile

After adding the version tag into the EG startup string
the itests are not recognizing that EG has started. This
updates the check with regex based on the new string pattern.

Update itests to check for new startup string

---

Makefile
docs/source/devinstall.md
etc/Makefile

The following targets are supported: kernelspecs_all, kernelspecs_yarn,
kernelspecs_conductor, kernelspecs_kubernetes, and kernelspecs_docker.
Also cleaned up the targets that get output when typing `make` and updated
the corresponding documentation.
Fixes #413

Create a separate kernelspecs tar for each resource manager

---

etc/docker/nb2kg/README.md

The README file that is posted on docker hub was slightly out of date.
These changes make appropriate updates and add mention of Jupyter Hub
in Alternative Uses.

Update nb2kg image README

---

etc/Makefile
etc/docker/enterprise-gateway/Dockerfile
etc/docker/kernel-py/Dockerfile
etc/docker/kernel-r/Dockerfile
etc/docker/kernel-scala/Dockerfile
etc/docker/kernel-spark-py/Dockerfile
etc/docker/kernel-spark-r/Dockerfile
etc/docker/kernel-tf-gpu-py/Dockerfile
etc/docker/kernel-tf-py/Dockerfile
etc/kernel-launchers/R/bootstrap/bootstrap-kernel.sh
etc/kernel-launchers/python/bootstrap/bootstrap-kernel.sh
etc/kernel-launchers/scala/bootstrap/bootstrap-kernel.sh
etc/kernelspecs/spark_R_kubernetes/bin/run.sh
etc/kernelspecs/spark_python_kubernetes/bin/run.sh
etc/kernelspecs/spark_scala_kubernetes/bin/run.sh

Rather than have a set of multiple language kernelspecs in each kernel-image,
this change only adds the appropriate _launcher files_ to each kernel image.
This enables applications to create their own kernelspec files for each of
the supported languages w/o requiring them to update the kernel-image or
have to share a volume with the kernel image in order to expose their kernel-spec.
Each kernel-image now contains a kernel-launchers/<language> directory in
/usr/local/share/jupyter.  There is no sibling kernels directory in these
images.  In addition, since the enterprise-gateway image needs to obtain the
actual name of the scala launcher files (since these contain version-specific
values), it too must have a kernel-launchers/scala directory (unfortunately).
NOTE: THIS PULL REQUEST SHOULD …

Add only appropriate launcher files to kernel images

---

enterprise_gateway/services/kernels/remotemanager.py
enterprise_gateway/services/processproxies/k8s.py
enterprise_gateway/services/processproxies/processproxy.py
enterprise_gateway/services/sessions/kernelsessionmanager.py

When the `KERNEL_USERNAME` is not provided in the kernel creation request,
the code that manages sessions would use a value of 'unspecified' while the
code that enforces limits would use the server's process username.  This
change uses a consolidated method so all locations render the same behavior
relative to defaulted values.
We will now also display the value of the kernel username when starting the kernel.
Note: These changes need to be merged into the 1.x branch where applicable.
Fixes #490

Fix max-kernels-per-user when KERNEL_USERNAME not set

---

enterprise_gateway/services/kernels/remotemanager.py
enterprise_gateway/services/processproxies/processproxy.py
etc/Makefile
etc/kernel-launchers/R/scripts/gateway_listener.py
etc/kernel-launchers/R/scripts/launch_IRkernel.R
etc/kernel-launchers/python/scripts/launch_ipykernel.py
etc/kernel-launchers/scala/toree-launcher/src/main/scala/launcher/ToreeLauncher.scala
etc/kernelspecs/R_docker/kernel.json
etc/kernelspecs/R_kubernetes/kernel.json
etc/kernelspecs/python_distributed/kernel.json
etc/kernelspecs/python_docker/kernel.json
etc/kernelspecs/python_kubernetes/kernel.json
etc/kernelspecs/python_tf_docker/kernel.json
etc/kernelspecs/python_tf_gpu_docker/kernel.json
etc/kernelspecs/python_tf_gpu_kubernetes/kernel.json
etc/kernelspecs/python_tf_kubernetes/kernel.json
etc/kernelspecs/scala_docker/kernel.json
etc/kernelspecs/scala_kubernetes/kernel.json
etc/kernelspecs/spark_R_conductor_cluster/kernel.json
etc/kernelspecs/spark_R_kubernetes/kernel.json
etc/kernelspecs/spark_R_yarn_client/kernel.json
etc/kernelspecs/spark_R_yarn_cluster/kernel.json
etc/kernelspecs/spark_python_conductor_cluster/kernel.json
etc/kernelspecs/spark_python_kubernetes/kernel.json
etc/kernelspecs/spark_python_yarn_client/kernel.json
etc/kernelspecs/spark_python_yarn_cluster/kernel.json
etc/kernelspecs/spark_scala_conductor_cluster/kernel.json
etc/kernelspecs/spark_scala_kubernetes/kernel.json
etc/kernelspecs/spark_scala_yarn_client/kernel.json
etc/kernelspecs/spark_scala_yarn_cluster/kernel.json

Replaced the `{connection_file}` parameter in the `kernel.json` files with
`--RemoteProcessProxy.kernel-id {kernel_id}` since the former parameter was
used solely to extract the kernel's ID and create a new file to hold the
connection information.
The scala and python launchers will still honor `{connection_file}` but give
preference to the new parameter if both are provided.  They will also issue a
warning in such cases indicating that `{connection_file}` is deprecated.
The R launcher, however, uses the `argparser` library which does not support
optional positional arguments (like `{connection_file}` now becomes).  As a
result, the R launcher doesn't support the previous form.  This should only
be a problem where there `kernel.json` has not been updated, but the launcher
has been updated …

Add kernel-id parameter, cleanup launchers

---

etc/docker/demo-base/Dockerfile
etc/docker/kernel-r/Dockerfile
etc/docker/kernel-spark-r/Dockerfile

Updated pulls for IRkernel v0.8.14 via CRAN.
Updated CRAN mirrors to be consistent across dockerfiles
Removed conda installation of IRkernel so all dockerfiles pull IRkernel from CRAN

Update IRkernel to pull from CRAN instead of Github

---

enterprise_gateway/client/gateway_client.py
enterprise_gateway/itests/test_python_kernel.py
enterprise_gateway/services/kernels/remotemanager.py

When EG restarts remote kernels, it creates a new set of ports.  This
was causing the activity_stream code, tied to iopub, to stop getting
updated.  This change starts a new activity-watcher on restarts of
RemoteProcessProxy instances.
Added the capability to fetch a kernel's activity for use in test code.

Reset watch-activity callback on remote-proxy restarts

---

enterprise_gateway/client/gateway_client.py
enterprise_gateway/itests/test_python_kernel.py
enterprise_gateway/services/kernels/remotemanager.py

These changes are a copy of those used in PR #514...
When EG restarts remote kernels, it creates a new set of ports. This
was causing the activity_stream code, tied to iopub, to stop getting
updated. This change starts a new activity-watcher on restarts of
RemoteProcessProxy instances.
Added the capability to fetch a kernel's activity for use in test code.
Fixes #513

Copy restart fix from 1.x (PR 514) to master

---

enterprise_gateway/enterprisegatewayapp.py

Hello! I made a small fix to add the ability to connect through the parameters of the command line a custom version of the KernelSessionManager class. For example, in order to be able to realize saving sessions not only in files, but also in SQL and NOSQL databases.

Adding the ability to use custom version of the KernelSessionManager class

---

enterprise_gateway/services/kernels/remotemanager.py
enterprise_gateway/services/sessions/kernelsessionmanager.py

current version have issue: 
after deserialization session modified in-place and can't serialize again
bug on path
1) pass connection_info in self.kernel_manager.start_kernel_from_session
2) kernel manager invoke km.load_connection_info(connection_info)
3) load_connection_info modify key in-place (convert str_to_bytes)
4) try store updated list of sessions in _commit_sessions cause serialization exception (can't store bytes)
what done:
1) localize work related how we serialize/deserialize data to storage in one place
2) for serialization/deserialization always create full copy of data, for prevent unexpected modification

fix save-restore for sessions

---

requirements.yml

when make virtual environment using `conda`
I have faced package not found error
```
$ make env
Fetching package metadata ...........
NoPackagesFoundError: Package missing in current osx-64 channels:
- kubernetes >=4.0.0
make: [env] Error 1 (ignored)
```
and I think it's because of `conda-forge` packages about [kubernetes](https://anaconda.org/conda-forge/python-kubernetes) and [docker](https://anaconda.org/conda-forge/docker-py)

update conda requirements

---

Makefile
etc/Makefile
etc/docker/enterprise-gateway/Dockerfile
etc/docker/kernel-py/Dockerfile
etc/docker/kernel-r/Dockerfile
etc/docker/kernel-scala/Dockerfile
etc/docker/kernel-spark-py/Dockerfile
etc/docker/kernel-spark-r/Dockerfile
etc/docker/kernel-tf-gpu-py/Dockerfile
etc/docker/kernel-tf-py/Dockerfile
etc/kernel-launchers/R/scripts/launch_IRkernel.R
etc/kernel-launchers/bootstrap/bootstrap-kernel.sh
etc/kernel-launchers/docker/scripts/launch_docker.py
etc/kernel-launchers/kubernetes/scripts/kernel-pod.yaml
etc/kernel-launchers/kubernetes/scripts/launch_kubernetes.py
etc/kernel-launchers/python/scripts/launch_ipykernel.py
etc/kernelspecs/R_docker/kernel.json
etc/kernelspecs/R_kubernetes/kernel.json
etc/kernelspecs/python_docker/kernel.json
etc/kernelspecs/python_kubernetes/kernel.json
etc/kernelspecs/python_tf_docker/kernel.json
etc/kernelspecs/python_tf_gpu_docker/kernel.json
etc/kernelspecs/python_tf_gpu_kubernetes/kernel.json
etc/kernelspecs/python_tf_kubernetes/kernel.json
etc/kernelspecs/scala_docker/kernel.json
etc/kernelspecs/scala_kubernetes/kernel.json
etc/kernelspecs/spark_R_kubernetes/bin/run.sh
etc/kernelspecs/spark_python_kubernetes/bin/run.sh
etc/kernelspecs/spark_scala_kubernetes/bin/run.sh
etc/kubernetes/enterprise-gateway.yaml

This change reorganizes the kernel-launcher and kernel-bootstrap files that are
used when launching kernel images.  These files are then packaged into a tar.gz
file that can be downloaded from github relative to a given release.
As a result of this reorganization, the kernel-launchers sub-directory has been
moved to be co-located with the `bootstrap-kernel.sh` located in /usr/local/bin
by default.  This directory can be changed by specifying a different value for
KERNEL_LAUNCHERS_DIR when starting the kernel image.
The kernel image CMD entries have also been defaulted to the bootstrap-kernel.sh
file so kernel images can be launched w/o having to specify a command.  However,
attempts to manually launch these images will fail unless envs `KERNEL_ID` and
`EG_RESPONSE_ADDRESS` have been …

Package kernel launcher files for custom kernel images

---

enterprise_gateway/itests/test_python_kernel.py
etc/kernel-launchers/python/scripts/launch_ipykernel.py

This fix addresses a bizarre issue introduced when the launcher started
passing the `local_ns` parameter to `embed_kernel()`.  Apparently, the
import statements from the launcher can side-effect the code running in
cells.  This was causing cells using `random()` to fail *downstream* in
an unusual fashion, so cells containing something like the SparkPi example
code would fail - despite the rest of the spark context working fine.
We eventually found that changing the launcher's `import random` to
`from random import random` sufficiently "fixed" things and SparkPi
example worked again.
Since we learned that confirming the spark context is properly
established is not sufficient, this commit also adds `test_run_pi_example`
to trigger some deeper interactions with Spark.

Fix launcher side effect

---

etc/Makefile
etc/docker/kernel-py/Dockerfile
etc/docker/kernel-r/Dockerfile
etc/docker/kernel-scala/Dockerfile
etc/docker/kernel-spark-py/Dockerfile
etc/docker/kernel-spark-py/README.md
etc/docker/kernel-spark-py/entrypoint.sh
etc/docker/kernel-spark-r/Dockerfile
etc/docker/kernel-spark-r/entrypoint.sh
etc/docker/kernel-tf-gpu-py/Dockerfile
etc/docker/kernel-tf-py/Dockerfile

- Both Spark-based Python and R kernel images will now use each respective
vanilla kernel as its base image
- Updated kernel-r dockerfile to use latest now that docker-stacks ISSUE-679
has been resolved
- Updated kernel-py docker file to use latest jupyter/scipy-notebook
- Conda support in both respective spark-based images now with more robust libraries
- Small misc fixes

Use vanilla kernel images as base for spark kernel images

---

enterprise_gateway/services/processproxies/processproxy.py

While performing local debugging (on mac) I found that errno 57 "socket is not connecte"
was being raised whenever EG went to shutdown and close the response socket that it no
longer needed.  Since the socket is no longer needed we should tolerate exceptions here.
This is probably a function of running the kernel locally as well as the operating system
(since this doesn't occur on RHEL systems).

Tolerate errors when closing response-socket

---

docs/source/config-options.md
docs/source/getting-started-kubernetes.md
enterprise_gateway/itests/test_python_kernel.py
enterprise_gateway/services/processproxies/container.py
etc/docker/enterprise-gateway-docker.sh
etc/docker/enterprise-gateway-swarm.sh
etc/kernel-launchers/docker/scripts/launch_docker.py
etc/kernel-launchers/kubernetes/scripts/kernel-pod.yaml

Added basic support for running as user id and group id values.  These values
can be specified via KERNEL_UID and KERNEL_GID respectively.  The defaults for
these values are 1000 (jovyan) and 100 (users) since that's how the containers
are built.  However, note that on k8s, use of `runAsGroup` requires that
feature-gate `RunAsGroup` first be enabled.  Failure to enable the feature-gate,
yet use either `runAsUser` or `runAsGroup` will result in the 0 (root) group
being the effective group of the container.  As a result, use of these attributes
are commented out in the `kernel-pod.yaml` file with an appropriate comment.
The docker launcher has also been extended for these applicable values in docker.
Although Kubernetes PodSecurityPolicy objects can be used to ensure that the
root …

Add support for run-as-UID/GID in containers

---

docs/source/config-options.md
enterprise_gateway/services/processproxies/container.py
etc/docker/enterprise-gateway-docker.sh
etc/docker/enterprise-gateway-swarm.sh
etc/docker/enterprise-gateway/start-enterprise-gateway.sh
etc/kernel-launchers/docker/scripts/launch_docker.py
etc/kernel-launchers/kubernetes/scripts/kernel-pod.yaml
etc/kernel-launchers/kubernetes/scripts/launch_kubernetes.py
etc/kubernetes/enterprise-gateway.yaml

Added the ability to mirror the notebook working directory by adjusting
the kernel container's working directory prior to its launch.  When
`KERNEL_WORKING_DIR` is provided **and** `EG_MIRROR_WORKING_DIRS=True`
Enterprise Gateway will set the container's working directory to the value
of `KERNEL_WORKING_DIR`.
For Notebook users, this change should be used with NB2KG versions >= 0.4.0
as `KERNEL_WORKING_DIR` will be set to the appropriate value automatically.
Because this feature requires coordinated volume mounts (typically of the
user's home directory) `EG_MIRROR_WORKING_DIRS` is disabled by default.
Also:
Updated docs with some recently added environment variables.
Adjusted default culling parameters in the EG containerized environments.
Fixes #570

Support kernel working dir

---

etc/kernel-launchers/kubernetes/scripts/kernel-pod.yaml

Wrong indentation for multiple line comments causes yaml parsing error.
This change corrects indentation of kernel-pod.yaml file.
Closes #575
Signed-off-by: Eunsoo Park <esevan.park@gmail.com>

Fixup! wrong indentation in kernel-pod.yaml

---

setup.py

With this change, kernelspec resources can be served to the notebook via NB2KG >= 0.5.0.

Bump JKG version for kernelspec resource change

---

enterprise_gateway/itests/test_python_kernel.py
enterprise_gateway/itests/test_r_kernel.py
enterprise_gateway/itests/test_scala_kernel.py

The restart test was ensuring that the state was idle or starting, but then we started seeing the busy state cause failures.  Since the very next statement is what actually confirms the restart occurred and won't execute until the kernel reaches the idle state, I decided we're better off without the state check entirely.

Fix itest restarts - remove state check

---

.travis.yml

Remove Python 2.x from Travis build
Remove Python 3.4 from Travis build
Build Python 3.5 and 3.6 python versions

Lightweight Travis CI builds

---

etc/docker/kernel-scala/Dockerfile
etc/docker/kernel-spark-py/Dockerfile
etc/docker/kernel-spark-r/Dockerfile

When changing the spark-based images to jupyter-based images, we dropped chown to `jovyan` for the SPARK_HOME/work-dir.  As a result, the jupyter-based images would get failures running spark jobs that required executors.  This change increases the permissions of the work-dir, not the owners, since we can run images as non-jovyan users today.
An image to test this with exists at: `kbates/kernel-spark-py:workdir`.

Increase write permissions on SPARK_HOME/work-dir

---

docs/source/getting-started-client-mode.md
docs/source/getting-started-cluster-mode.md
docs/source/troubleshooting.md
enterprise_gateway/itests/test_python_kernel.py
enterprise_gateway/tests/notebook_http/swagger/test_parser.py
enterprise_gateway/tests/test_jupyter_websocket.py
etc/docker/demo-base/Dockerfile
etc/docker/demo-base/README.md
etc/kernelspecs/dask_python_yarn_remote/kernel.json
etc/kernelspecs/python_distributed/kernel.json
etc/kernelspecs/spark_R_yarn_client/kernel.json
etc/kernelspecs/spark_R_yarn_cluster/kernel.json
etc/kernelspecs/spark_python_yarn_client/kernel.json
etc/kernelspecs/spark_python_yarn_cluster/kernel.json
setup.cfg
setup.py

Jupyter has pledged to drop support for Python 2.x
and Jupyter Enterprise Gateway is going on the same
direction as several other Jupyter projects that have
already droped support for Python 2.x in favor of
Python 3.5 and above.
The following changes are part of this effort:
* Remove 'universal' flag for EG wheel distribution
* Remove conditional PY2/PY3 code
* Default kernelspec configurations to use version agnostic
values
* Update CI builds to only run tests on Python 3.5 and above
environments
Fixes #573

Drop support for Python 2.x

---

docs/source/getting-started-cluster-mode.md
docs/source/system-architecture.md
enterprise_gateway/enterprisegatewayapp.py
enterprise_gateway/services/processproxies/yarn.py
etc/docker/enterprise-gateway-demo/start-enterprise-gateway.sh.template

This pull request is a split of PR #607 that changes the default value for the YARN endpoint configuration option to `None`.  By doing this, 90% of customers can take advantage of built-in behaviors in `yarn-api-client` which determine the YARN Resource Manager endpoint from local configuration files.  This is because 90% of customers install Enterprise Gateway on an edge node of their YARN cluster.  In addition, that logic will also handle the case where YARN is configured for HA.
Installations on which Enterprise Gateway is not installed on an edge node, will still need to provide a YARN endpoint parameter.  In addition, these installations cannot take advantage of HA configurations until [yarn-api-client PR #29](https://github.com/toidi/hadoop-yarn-api-python-client/pull/29) is merged.

Set YARN endpoint default to None

---

docs/environment.yml
docs/source/conf.py
requirements.yml

While the recently added (#625) Helm configuration documentation table renders [just fine on GitHub](https://github.com/jupyter/enterprise_gateway/blob/master/docs/source/getting-started-kubernetes.md#configuration), it [does not appear to render correctly on Read the Docs](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/getting-started-kubernetes.html#configuration). (My bad for not testing it there.)
This change adds a Sphinx extension called `sphinx-markdown-tables` that turns the pile of unrendered table Markdown into a nicely rendered table with no other changes to the Markdown.
Fixes #631.
Manually installed `sphinx-markdown-tables` into an existing Enterprise Gateway virtualenv, activated the virtualenv, and then ran `sphinx-markdown-tables`. Observed that the table now …

Fix Markdown table rendering in documentation. (#631).

---

docs/source/getting-started-kubernetes.md
etc/kubernetes/helm/Chart.yaml
etc/kubernetes/helm/templates/deployment.yaml
etc/kubernetes/helm/values.yaml

This PR provides a way to mount kernelspecs into an Enterprise Gateway Kubernetes pod from a custom kernelspecs Docker image. This is an alternative to mounting kernelspecs into an Enterprise Gateway K8s pod via an NFS server. The motivation is twofold:
* Setting up, maintaining, and deploying kernelspecs to an NFS server is kind of a pain, especially within Kubernetes.
* It'd be super nice for usability if a Helm "release" (Helm's terminology for a deployment) included everything necessary to get Enterprise Gateway up and running.. including kernelspecs. No multiple-step deploys. This works today with the stock kernelspecs (just deploy EG and go), but it'd also be nice if this worked for custom kernelspecs.
See https://github.com/jupyter/enterprise_gateway/pull/635 for more background. …

Use a custom image as an init container to copy in kernelspecs.

---

etc/docker/demo-base/Dockerfile

Spark 2.4.1 was removed from the mirror site we used, so this change points us to the archive.  Now it will be our responsibility to move to specific Spark versions rather than getting forced to move.

Update demo-base to download Spark distro from archive

---

docs/source/getting-started-kubernetes.md
etc/kubernetes/helm/templates/ingress.yaml
etc/kubernetes/helm/values.yaml

My stab at #626. 
- Ingress template is parameterized with a boolean to enable/disable. 
- Default is set to assume user is using nginx as ingress controller.
Working on including Istio as well.

Add ingress resource to helm chart

---

Makefile
docs/source/getting-started-kubernetes.md
etc/Makefile
etc/docker/kernel-image-puller/Dockerfile
etc/docker/kernel-image-puller/README.md
etc/docker/kernel-image-puller/kernel_image_puller.py
etc/docker/kernel-image-puller/requirements.txt
etc/kubernetes/enterprise-gateway.yaml
etc/kubernetes/helm/templates/daemonset.yaml
etc/kubernetes/helm/templates/deployment.yaml
etc/kubernetes/helm/templates/service.yaml
etc/kubernetes/helm/values.yaml
release.sh

This adds support for a _Kernel Image Puller_ image, meant to be run in a DaemonSet, that will periodically gather the set of configured kernel image names from Enterprise Gateway and pull the image that image to the node on which it is running.  Since it's configured as a DaemonSet, it will be running on each node (as well as started on newly added nodes) of the cluster.  This idea was discussed in #638.
The configurable items are all established via environment variables since that is the natural way to use parameters in container configurations.  These include:
-  **`KIP_INTERVAL`:** the number of seconds at which it waits before performing the operation again.  Default is every 5 minutes (`300`)
- **`KIP_NUM_PULLERS`:** the number of threads active at any given time operating from a …

Add daemon to pull kernel images to each node

---

etc/docker/enterprise-gateway/Dockerfile
etc/docker/kernel-spark-py/Dockerfile
etc/docker/kernel-spark-r/Dockerfile

Downloading from mirrors causing problems when they update too frequently and delete older distributions.

Update Apache Spark download URL with official archive instead of mirror

---

enterprise_gateway/enterprisegatewayapp.py
enterprise_gateway/services/sessions/kernelsessionmanager.py

This change does some minor refactoring of `KernelSessionManager` such
that it is now a base class with two abstract methods.  A new subclass,
`FileKernelSessionManager`, has been created to provide an example subclass
which writes to a file.  This will be the default implementation.
Other forms of persistence are encouraged, namely NoSQL or KV providers.
To use a different kernel session manager add the following to the EG
command line (or configuration file equivalent):
`--EnterpriseGatewayApp.kernel_session_manager_class=<MyKernelSessionManager>`
Note there may be some additional refactoring required once we determine
the needs for other kinds of persistence.
Fixes #644

Refactor KernelSessionManager to accommodate various persistence methods

---

Makefile
etc/Makefile
requirements.yml

Since we should build our published images from scratch (and not rely
on anything in the docker-cache), the following changes were made:
1. Added proper support to set the NO_CACHE macro.  Previously, this
was set to `--no-cache` but then not referenced in the docker build
rules. Instead, the default should be an empty value (`NO_CACHE?=`)
and have this "empty variable" referenced by the docker build target.
2. Changed the publish-* targets to push-* since all publish-* did was
push existing images.
3. Created a publish-images target that is responsible for performing
the full builds and pushes of all images. This target will set
NO_CACHE=--no-cache.
4. Unrelated. Found that sphinx-markdown-tables was preventing the
creation of new conda environments.  Since this is only for docs and …

Makefiles: change publish targets to push, use --no-cache on new publish-image target

---

docs/source/kern-yarn-cluster-mode.md
docs/source/system-architecture.md
enterprise_gateway/enterprisegatewayapp.py
enterprise_gateway/services/processproxies/yarn.py
requirements.yml
setup.py

Add support for specifying multiple YARN resource managers for HA-configured environments.  A new configuration option `alt_yarn_endpoint` compliments `yarn_endpoint` when YARN HA configurations are in use.  When both values are provided, the `yarn-api-client` library will the original config value for an active RM.  If not active, the library will check the alternate.
Note that both of these configuration values default to `None` (`yarn_endpoint` has been updated for this).  In cases where `yarn_endpoint` is `None`, the `yarn-api-client` library will read from the `yarn-site.xml` file located in `HADOOP_CONF_DIR` and choose the active resource manager - both HA and non-HA configurations.
This pull request is dependent on the [yarn-api-client PR …

Add support for multiple YARN resource managers

---

enterprise_gateway/itests/test_python_kernel.py
etc/kernel-launchers/python/scripts/launch_ipykernel.py

When performing CPU-intensive operations within a cell, remote python
kernels can have their interrupt capabilities stop working due to
thread starvation.  This is because the gateway-listener thread is
unable to signal the kernel.  This change uses a `Process` rather
than a `Thread` in which to run the gateway-listener - which results
in it not being starved.  As a result, the signal can be sent to the
kernel and the cell's operation interrupted.
Fixes #682

Fix interrupts on intensive operations

---

etc/docker/enterprise-gateway/start-enterprise-gateway.sh
etc/kubernetes/enterprise-gateway.yaml
etc/kubernetes/helm/enterprise-gateway/templates/deployment.yaml
etc/kubernetes/helm/enterprise-gateway/templates/ingress.yaml
etc/kubernetes/helm/enterprise-gateway/values.yaml

Add ability to specify value for `EG_PORT` env variable
from its default value (`8888`) to another value. This
can be done via the eg yaml file or helm charts.
Also removed the port field from the ingress stanza in
the helm values and updated ingress to use `Values.port`
since that's the service port anyway.
Fixes #684

Allow port overrides in Kubernetes deployments

---

.travis.yml
etc/Makefile

Ran a series of different trials to try to figure this out.  There were two
primary issues.
1. nosetests were completing, but travis was not detecting that the nosetests
had completed.  So it never produced the green status that the test completed.
2. The build of the demo-base was encountering "github api rate limit" errors
when attempting to install SparkR.
Issue 1 appears to be (more frequently) resolved by using `travis_wait` with
a 3 minute timeout.  After 3 minutes it seems like travis breaks out of its
"coma" and sees that the the nosetests completed OK. Note: Detection of a
succesful nosetest in these "timeout" situations is still intermittent. I will
likely enlist the help of the travis team on this issue.
Issue 2 can be resolved by pushing demo-base to docker hub and NOT …

Attempt to address build flakiness

---

etc/docker/demo-base/Dockerfile

1. Mirror link to Hadoop distribution was using EU mirror instead of US.
2. Updated SparkR package installation to use CRAN instead of github. Included r-versions package to allow us to select specific SparkR package versions.

Update link to use CRAN installation for Apache Spark

---

.travis.yml

Add travis_retry prior to nosetests.  This will retry any iteration
that returns non-zero up to 3 times.  This will hopefully eliminate
intermittency issues and only propagate true failures.
Added travis_retry for building the demo image since that's another
area that has a tendency to be flakey.
Here's a travis log that performed one retry of the nosetests (that originally were successful, but travis_wait timed out). https://travis-ci.org/kevin-bates/enterprise_gateway/jobs/547483362

More build adjustments - use travis_retry to reduce intermittency

---

enterprise_gateway/itests/test_python_kernel.py
etc/kernel-launchers/python/scripts/launch_ipykernel.py

The python kernel launcher was not initializing the namespace used
in the embed_kernel properly.  This change reverts an earlier change
to use the spark context variables from the global scope, instead
moving them to the local namespace.
Thanks to @jcrist for significant insight and guidance!
Fixes #687

Fix scoping issues relative to python kernels on Spark

---

docs/source/docker.md
docs/source/getting-started.md
docs/source/kernel-distributed.md
docs/source/kernel-kubernetes.md
docs/source/kernel-spark-standalone.md
docs/source/kernel-yarn-client-mode.md
docs/source/kernel-yarn-cluster-mode.md
release.sh

The release.sh script leaves doc links in an odd state where a
non-existent dev version will refer to the latest release version.
Instead, it would be better to just let the latest docs always
reference the last published release.  Then all links work and
there's no confusion.
Introduced notion of 'previous version' to release.sh so that
such links can be updated to the new release.  In addition, there
is no 'reset to development' in the docs - otherwise invalid
links will get produced.

Fix doc links and release script

---

Makefile
docs/source/kernel-kubernetes.md
etc/kubernetes/helm/enterprise-gateway/Chart.yaml
release.sh

Added more (hopefully useful) metadata to the Chart.yaml file that
includes making the version of the chart match that of the EG release.
Modified the release.sh to update the version information in the chart.
Added `helm-chart` target to Makefile and tied to `dist` target.
Updated docs to reference helm chart tarball on release page.
Fixes #656

Add helm chart tarball to distribution

---

docs/source/config-options.md
enterprise_gateway/enterprisegatewayapp.py

-- Adding option to set ws_ping_interval variable for notebook server usages.

Zmq port setting

---

enterprise_gateway/enterprisegatewayapp.py

In Current code, EG is not terminating gateway server process when handling SIGTERM signal. It is killing any running kernels correctly but the main process is not being killed.
In this fix, sending SIGTERM will kill any running kernels and will shutdown the gateway server as well.
**Closing issues**
Fixes #701 
Closes #701

Termination of EG in SIGTERM

---

Makefile
enterprise_gateway/itests/test_scala_kernel.py

The interrupt test timeout for scala was 30 seconds.  Since spark context
initialization can sometimes take longer (on systems with limited resources)
the test was failing - then causing subsequent failures.  Extending to 60
seconds resolves that issue.
Also changed how `VERSION` is set in the Makefile so it can be set outside
the Makefile in order to use different image versions, etc.
**Commit Formatting**
Please follow the **[seven rules of a great commit message](https://chris.beams.io/posts/git-commit/)**
- Separate subject from body with a blank line
- Limit the subject line to 50 characters
- Capitalize the first word of the subject line
- Do not end the subject line with a period
- Use the imperative mood in the subject line
- Wrap the body at 72 characters
- Use the body to …

Extend scala interrupt test timeout

---

etc/kernel-launchers/R/scripts/launch_IRkernel.R

Previously, the customAppName parameter defaulted to 'SparkR'.  This
resulted in it always being set.  This change removes the default, then
only if a parameter was not provided, does it default to the kernel_id
parameter.

Default the SparkR app name to kernel id if not provided

---

docs/source/troubleshooting.md
enterprise_gateway/services/processproxies/processproxy.py

* Retrieve user credentials only when using ssh
* Document troubleshooting steps for OpenShift Kubernetes environment
Fixes #705 
**Waiting user validation before pushing to master**

Multiple fixes to enable EG on OpenShift Kubernetes Environment

---

enterprise_gateway/services/kernels/remotemanager.py
enterprise_gateway/services/processproxies/distributed.py
enterprise_gateway/services/processproxies/processproxy.py
enterprise_gateway/services/processproxies/yarn.py
etc/kernel-launchers/R/scripts/gateway_listener.py
etc/kernel-launchers/python/scripts/launch_ipykernel.py
etc/kernel-launchers/scala/toree-launcher/src/main/scala/launcher/ToreeLauncher.scala

While looking into #701, I noticed that kernels where not being shutdown
in a graceful manner, sometimes leaving orphaned processes and running
YARN applications.  These issues would occur in normal shutdowns and as
the result of EG termination.  This commit includes the following changes:
1. Added call to shutdown listener from cleanup to account for EG termination
since the SIGTERM handler uses an immediate kill code path.
2. DistributedProcessProxy now sends additional SIGTERM to listener prior
to its shutdown.  This addresses the orphaned kernel processes.
3. Refactored methods to send listener commands.
4. Updated launchers to handle multiple commands in a single request.
5. Removed or cleaned up log statements.

Cleanup kernel shutdown

---

enterprise_gateway/services/processproxies/yarn.py
requirements.yml
setup.py

Raising an Initial PR for this issue:- 
https://github.com/jupyter/enterprise_gateway/issues/664
There is a seperate PR to be raised on yarn-api-client repo. We can have a discussion on this PR before moving on another one.

Kernel Startup using Yarn with resource and request check

---

etc/kernel-launchers/kubernetes/scripts/launch_kubernetes.py

Using `load_all()` without specifying a loader is unsafe and produces a deprecation warning.  Replacement with `safe_load_all()` satisfies the warning since safe loads prevent certain inherently unsafe operations.
Fixes  #714

Use safe_load_all() to fix deprecation warning

---

etc/kernel-launchers/scala/toree-launcher/build.sbt

Moves to use the official maven artifact from maven central where the
artifact pom with the list of dependencies and transient dependencies
is available.

Retrieve Toree jar from maven repository

---

enterprise_gateway/services/processproxies/yarn.py

Yarn Application's `FAILED` state is not added into final_states for some reason. The user would only see kernel launch getting timed out but not an error related to `FAILED` state. `FAILED` state is pretty common in Yarn and it needs to be handled. 
Closes #708.

1. Adding yarn application state 'FAILED' into final_states 2. Closes #708

---

requirements.yml
setup.py

In order to allow Notebook 6.x dependencies, there was a need to
fix some compatibility issues in Jupyter Kernel Gateway.

Allow Notebook 6.x dependency

---

enterprise_gateway/client/gateway_client.py

Formally attempt to terminate response-reader thread.  Thought this might help eliminate potential intermittent hangs in the test cases.

Terminate response reader thread in integration tests

---

etc/docker/demo-base/Dockerfile

This was found when building demo-base image in preparation for
2.0 release (#723).

Switch to root when installing python packages

---

enterprise_gateway/enterprisegatewayapp.py

Fix to resolve startup error on Windows:
(base) v:\bin>jupyter enterprisegateway
[I 2019-08-31 16:45:22.305 EnterpriseGatewayApp] Jupyter Enterprise Gateway 1.2.0 is available at http://127.0.0.1:8888
Traceback (most recent call last):
File "C:\Anaconda3\Scripts\jupyter-enterprisegateway-script.py", line 9, in <module>
sys.exit(launch_instance())
File "C:\Anaconda3\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
File "C:\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
app.start()
File "C:\Anaconda3\lib\site-packages\enterprise_gateway\enterprisegatewayapp.py", line 278, in start
signal.signal(signal.SIGHUP, signal.SIG_IGN)
AttributeError: module …

fix: AttributeError: module 'signal' has no attribute 'SIGHUP'

---

docs/source/kernel-kubernetes.md
etc/kubernetes/helm/enterprise-gateway/templates/ingress.yaml
etc/kubernetes/helm/enterprise-gateway/values.yaml

Went ahead and added traefik ingress example to helm charts.  I've also made it the default over nginx since I believe enterprises will likely use traefik (and it works for me).  Found during 2.0 inspection (#723)

Add support for traefik ingress

---

enterprise_gateway/services/processproxies/yarn.py
setup.py

This release provides the ability to honor the full endpoint set from the command line and include https.
Fixes: #729

Update to new yarn-api-client API release 1.0

---

.travis.yml

Our builds are currently failing on the integration tests that use the `spark_scala_yarn_client` and `spark_scala_yarn_cluster` kernels.  The reason is that the toree-launcher jar file build fails, but because we don't issue `make clean`, the subsequent build attempts "pass" because of a dependency issue (which we should figure out).  However, because each build should be like the first, we should add the `clean` target when building the distribution and docker image.
Once this is done, the builds should fail early (after 3 failed build attempts), rather than continue only to fail 25 minutes later.

Perform clean on each build attempt

---

docs/source/config-options.md
enterprise_gateway/enterprisegatewayapp.py
enterprise_gateway/tests/test_enterprise_gateway.py
setup.py

This change leverages a recent update to the traitlets library
that exposes an application's loaded configuration files.  When enabled
(via a positive value for `dynamic_config_interval`) it periodically
checks the loaded configuration files for updates (via file modification
times).  If updates are detected, the registered configurables are
updated with the contents of the files.  See documentation for more details.
Fixes #647

Add support for dynamic configurations

---

enterprise_gateway/services/api/swagger.json
enterprise_gateway/services/api/swagger.yaml

Added `env` to the kernel POST definition and `metadata`
to the kernelspec definition for each of the swagger docs.
Fixes: #754

Update kernel post and kernelspec api definitions

---

etc/docker/kernel-scala/Dockerfile
etc/docker/kernel-spark-py/Dockerfile
etc/docker/kernel-spark-r/Dockerfile

On more recent versions of Kubernetes with Spark installed (prior to
2.4.5 or 3.0.0), the spark driver will request additional executors
and that request will fail (with 403).  These changes update the
spark-based images with an updated kubernetes client version that
addresses this issue.  See https://issues.apache.org/jira/browse/SPARK-28921
for more information.

Update k8s client in spark-based images

---

requirements.yml
setup.py

Significant changes are required to move to the 1.x release of yarn-api-client so we should cap it.
Note this change is only for the 1.x branch!

Cap yarn-api-client at < 1.0

---

enterprise_gateway/services/kernels/remotemanager.py

The new jupyter_client cache_ports attribute should be disabled since this
doesn't apply to remote kernels and is not compatible with the port-range
support added by EG.  As a result, it's best to just unconditionally disable
the functionality.
Resolves #786

Disable cache_ports

---

enterprise_gateway/services/processproxies/processproxy.py
etc/kernel-launchers/python/scripts/launch_ipykernel.py
requirements.yml
setup.py

The pycrypto package has fallen out of maintenance, so this change
replaces it with pycryptdomex.  This package was chosen over pycryptodome
because it can co-exist with pycrypto, while pycryptodome cannot, and
we felt other applications may be using pycrypto.  If the remote kernel
launchers are not updated, the two are compatible since we use
the same mode.

Replace pycrypto with pycryptodomex

---

.gitignore
enterprise_gateway/services/kernels/handlers.py

Use APIHandler write_error routine for ZMQChannelsHandler and avoid jinja2 templates.
Added .vscode folder to .gitignore.
Fixes: #797 .
Tested manually.
Not the most elegant of fixes. In an ideal world perhaps ZMQChannelsHandler (from another package) might be subclassed rather than monkey patched.

fix 'jinja2_env' if kernel does not exist

---

etc/kernel-launchers/python/scripts/launch_ipykernel.py
setup.py

Since many Hadoop YARN envs still run Python 2, we should continue
to make launchers compatible with Python 2 for the time being.
Resolves #807

Make python launcher compatible with python 2

---

enterprise_gateway/services/processproxies/processproxy.py
setup.py

Due to the complexities involving mixing async/await and gen.coroutine/yield
constructs, it's best to keep EG pinned to the pre-async notebook releases (6.0.*)
until EG can adopt async kernel management.
Removed a couple of redundant debug statements.
Resolves #806

Prepare for next notebook release, pin to current

---

enterprise_gateway/services/kernels/remotemanager.py
enterprise_gateway/services/sessions/sessionmanager.py
setup.py

This commit supersedes the commit from PR #809.  The real issue
was that the `maybe_future` wrappers didn't account for the case
that they could be wrapping async/await-based methods and not
just gen.coroutines.  Updating to use the wrapper from the notebook
utilities allows EG to work with current and future notebook releases.
Resolves #806

Prepare for next notebook release

---

etc/docker/enterprise-gateway/Dockerfile
etc/docker/kernel-py/Dockerfile
etc/docker/kernel-tf-gpu-py/Dockerfile
etc/docker/kernel-tf-py/Dockerfile

This commit addresses some recent changes and ensures the `future`
package is installed and replaces `pycrypto` with `pycryptodomex`.
Once merged, I think we can move forward with cutting 2.1.1.

Fix python-based images relative to recent changes

---

docs/source/index.rst
docs/source/kernel-library.md
docs/source/use-cases.md
enterprise_gateway/enterprisegatewayapp.py
enterprise_gateway/mixins.py
enterprise_gateway/services/kernels/remotemanager.py
enterprise_gateway/services/processproxies/conductor.py
enterprise_gateway/services/processproxies/distributed.py
enterprise_gateway/services/processproxies/processproxy.py
enterprise_gateway/services/processproxies/yarn.py
enterprise_gateway/tests/test_enterprise_gateway.py

This is a WiP.
So first pass, I just wanted to get things working, and they do (with nbclient, not sure if gatewayapp still works, but it should). There's way too much asking for permission in the code right now, and there's probably a lot that could be done to separate code where mappingkernelmanagers are needed. Another option is to make a single kernel mapping manager (AKA a completely useless stupid class) just for convenience.
What do you think about doing traitlets like this? To properly share it with EG App, I'll need to add this mixin and remove the included traitlets from EG App.

First pass at making RemoteKernelManager independent

---

etc/docker/enterprise-gateway/Dockerfile
etc/docker/kernel-image-puller/kernel_image_puller.py
etc/docker/kernel-scala/Dockerfile
etc/docker/kernel-spark-py/Dockerfile
etc/docker/kernel-spark-r/Dockerfile

- Updated the Spark version to 2.4.5 (and removed previous workaround).
- Fixed user creation commands in kernel-scala image build.
- Updated Kernel Image Puller to check for previously pulled image's existence and perform pull if not found.  This enables installations to use 'if not present' policy more accurately.
- Fixed up the location of `tini` (to /usr/bin) for Python and R spark images.
Fixes #802 
Fixes #804 
Fixes #805

Move images to Spark 2.4.5, other fixups

---

enterprise_gateway/enterprisegatewayapp.py
enterprise_gateway/services/kernelspecs/handlers.py

This change takes into consideration the globally-defined authorization lists that span kernelspecs.  It is a follow-on PR to #800.
Unauthorized users from both kernelspecs and globally-defined are treated as a union, while authorized users defined in a kernelspec can only use those kernels unless there are no globally-defined authorized users or they also appear in the global list as well.  As such, kernelspec authorization is considered before global authorization.
Here are some examples from a recent run...
Global Authorized Users = "bob, angel"
Global Unauthorized Users = "badguy"
Kernelspecs spark_python_yarn_* and spark_r_yarn_* have configured authorization lists.
User 'alice' is specifically authorized for spark_python_yarn_*
User 'angel' is not specifically listed in any …

Consider global authorization lists when filtering kernelspecs

---

enterprise_gateway/services/kernels/remotemanager.py

We have found that reverting the context in jupyter_client to its global form (from a year ago) doesn't lead to FD leaks.  The change away from the global context fixed an issue with multi-threaded kernel client applications, which EG probably doesn't need.
This change adds a configurable option (use_global_zmq_context=True) to enable the use of a global (singleton) context.  By default, the current behavior in jupter_client is used.
The reason this is configurable is that jupyter_client may soon release a change that would cause things to break if a global context was in use and we'd need to have a means of using jupyter_client's context directly - which a 'False' value permits.
To enable the use of the global ZMQ context, either of the following options must be taken...
Add to the …

Add option to use global ZMQ context

---

enterprise_gateway/services/processproxies/container.py

I removed the logic to check whether container_status is None,
because EG couldn't restart kernels although connections exists.
Fixes #827

Remove the logic to check whether container_status is None

---

enterprise_gateway/services/processproxies/distributed.py
enterprise_gateway/services/processproxies/processproxy.py

The original addition of shutdown_listener in RemoteProcessProxy.cleanup() for #707 was overzealous and side-affected container-based platforms.  This change moves that addition to DistributedProcessProxy since that is the only process proxy that needs this.
Fixes #822

Move shutdown_listener call in cleanup to DistributedProcessProxy

---

etc/docker/kernel-image-puller/kernel_image_puller.py

While testing the async kernel management PR I found that the Kernel Image Puller (KIP) was encountering a connection timeout in its initial attempt to get kernelspecs from the EG service.  When encountered, it waits for the prescribed interval - which defaults to 5 minutes before retrying.  However, the reason for the timeout is because EG had completely started yet.  
This change waits for 5 seconds and will continue on a 5-second poll until it can get kernelspecs.  Once kernelspecs have been found, it sets the wait interval to the configured value (default 300 seconds).  This way, the kernel images are pulled much sooner.
Testing shows the initial 5 second wait is sufficient.  However, the "right" change is to probably use an init container that exits only after the EG service is …

Delay KIP startup to prevent race against EG startup

---

docs/source/kernel-kubernetes.md
etc/docker/enterprise-gateway/start-enterprise-gateway.sh
etc/kubernetes/enterprise-gateway.yaml
etc/kubernetes/helm/enterprise-gateway/templates/deployment.yaml
etc/kubernetes/helm/enterprise-gateway/values.yaml

Adds appropriate plumbing (via environment variable `EG_DEFAULT_KERNEL_NAME`) to adjust the default kernel name in container environments and initializes those configurations with the appropriate python kernel.
Fixes #823

Enable ability to set default kernel name in container envs

---

enterprise_gateway/services/processproxies/processproxy.py
enterprise_gateway/services/processproxies/yarn.py

In some cases, the response_socket remains open.
I Identified a few cases and fix it
(currently, the response_socket is randomly selected each time a new kernel is created, therefore this issue was not detected)

 response_socket remains open

---

enterprise_gateway/services/kernels/remotemanager.py

This is now default behavior in jupyter_client versions 5.3.5 and
6.1.5 and makes the previous change obsolete. This rolls back #820.

Rollback option to use ZMQ global context

---

etc/docker/enterprise-gateway/start-enterprise-gateway.sh

While testing the fix released in #833, I found that `GET` requests against `/api/kernels` were throwing `403` because the listing of kernels was not enabled.  This change defaults the corresponding env (`EG_LIST_KERNELS`) to true for containerized uses.  It can still be disabled via the env for users not wishing to expose that information.

Allow kernel listings by default for EG containers

---

etc/docker/enterprise-gateway/Dockerfile
etc/docker/kernel-py/Dockerfile
etc/docker/kernel-r/Dockerfile
etc/docker/kernel-tf-py/Dockerfile

It was found that more recent base images (from [jupyter stacks](https://github.com/jupyter/docker-stacks)) are breaking the spark-based images that derive from them.  It is suspected that the move from conda 4.8.2 to 4.8.3 is side-effecting Spark in some manner.  
This change pins ALL jupyter-stack images to the same tag (commit) for consistency even though some images are not used in a Spark context.

Pin jupyter-stack images to known working version

---

docs/environment.yml
docs/source/conf.py
docs/source/contrib.md
docs/source/debug.md
docs/source/devinstall.md
docs/source/getting-started.md
docs/source/kernel-conductor.md
docs/source/kernel-local.md
docs/source/kernel-yarn-client-mode.md
docs/source/troubleshooting.md
requirements.yml
setup.py

Sphinx 3.0+ was breaking doc builds because we were still using deprecated items (source_parsers) that were deprecated in 1.8 and removed in 3.0.  This change updates those and restores references to .md files where we can (still can reference an anchor w/o .html).
This PR is coming from this repo because I needed to temporarily point at the `fix-doc-build` branch to ensure docs were building correctly.

Fix doc builds

---

docs/source/troubleshooting.md
etc/docker/demo-base/Dockerfile

Spark/PySpark 2.4.x dependency cloudpickle.py has an issue with
Python 3.8 which is described in SPARK-29536 and is only fixed
on Spark 3.0.
Fixes #859

Force Python 3.7 to avoid PySpark 2.4.x limitation

---

enterprise_gateway/services/kernels/handlers.py
enterprise_gateway/services/kernels/remotemanager.py
enterprise_gateway/services/processproxies/processproxy.py

Now that kernel startup within EG is asynchronous, there is an inherent race condition that occurs when attempting to enforce max kernel limits when kernel starts require any additional time and there are _simultaneous_ start requests received.  These changes include _pending_ start requests in the limit enforcement, taking an optimistic approach that _pending_ requests will be satisfied.
Fixes #855

Fix race condition during max kernel limit enforcement

---

Makefile

The recent changes to tag demo-base with the SPARK_VERSION rather than the release didn't quite handle the case where `make docker-images` is used - which produces a release-based tag for demo-base.  This minor change fixes that.  Here's the output of `make -n docker-images` (note the different TAG value for demo-base and the rest):
```
$ make -n docker-images
make WHEEL_FILE=dist/jupyter_enterprise_gateway-2.3.0.dev1-py2.py3-none-any.whl VERSION=2.3.0.dev1 NO_CACHE= TAG=2.4.6 SPARK_VERSION=2.4.6 -C etc demo-base
make WHEEL_FILE=dist/jupyter_enterprise_gateway-2.3.0.dev1-py2.py3-none-any.whl VERSION=2.3.0.dev1 NO_CACHE= TAG=dev SPARK_VERSION=2.4.6 -C etc enterprise-gateway-demo
make WHEEL_FILE=dist/jupyter_enterprise_gateway-2.3.0.dev1-py2.py3-none-any.whl VERSION=2.3.0.dev1 NO_CACHE= …
```

Fix build to produce correctly tagged image of demo-base

---

docs/source/kernel-kubernetes.md
etc/kubernetes/enterprise-gateway.yaml
etc/kubernetes/helm/enterprise-gateway/templates/clusterrole.yaml
etc/kubernetes/helm/enterprise-gateway/templates/clusterrolebinding.yaml

Update the reference for apiVersion used in rbac authorization definitions to use the `v1` release and not `v1beta1` which has been deprecated.
Fixes #869

Update deprecated reference in rbac apiVersion

---

enterprise_gateway/services/kernels/remotemanager.py
enterprise_gateway/tests/test_enterprise_gateway.py

Steps to reproduce:
1. Deploy enterprise gateway to Kubernetes cluster.
2. Create new kernel with a provided `KERNEL_ID` env var:
```bash
curl -i -X POST -d'{"name": "python_kubernetes", "env":{"KERNEL_ID": "1884ef38-9742-4322-a62d-004f57b1c36d"}}' http://192.168.99.108:30418/api/kernels
HTTP/1.1 201 Created
Server: TornadoServer/6.0.4
Content-Type: application/json
Date: Thu, 17 Sep 2020 07:36:34 GMT
X-Content-Type-Options: nosniff
Location: /api/kernels/d5294503-b97d-480a-afe2-8e14be1f7735
Content-Length: 172
{"id": "d5294503-b97d-480a-afe2-8e14be1f7735", "name": "python_kubernetes", "last_activity": "2020-09-17T07:36:37.819687Z", "execution_state": "starting", "connections": 0}
```
Kernel should be created with the ID value provided (`1884ef38-9742-4322-a62d-004f57b1c36d`), but the …

Fix Kubernetes kernel ID env var bug

---

etc/kubernetes/helm/enterprise-gateway/templates/deployment.yaml

Specifically when a kernel spec image is specified, emptydir get generated which is not valid, emtyDir is.

Kubernetes Deployment Typo

---

enterprise_gateway/services/processproxies/conductor.py
enterprise_gateway/services/processproxies/distributed.py
enterprise_gateway/services/processproxies/processproxy.py
enterprise_gateway/services/processproxies/yarn.py

Turns out we cannot convert the EG process-proxy process-based methods (e.g., `kill()`, `poll()`) because they are not async to begin with, nor are the `jupyter_client` methods (e.g., `send_signal()`, `cleanup()`) that call them.  Since the "mishmash" of `kill()` methods were constrained to just that method, it's best to make it synchronous and use `time.sleep()` for its polling - where needed.  However, when the process-proxy `kill()` is called from an async method - like `handle_timeout()`, we will wrap its call in `asyncio.get_event_loop().run_in_executor()`, which can be awaited, thereby retaining async behavior where it's really necessary.
Fixes #882

Make kill() a sync method

---

docs/source/config-options.md
enterprise_gateway/services/processproxies/yarn.py

https://github.com/jupyter/enterprise_gateway/issues/887
This PR enables passing the CA bundle path to yarn_api_client Resource manager under the `verify` variable if the said path is exported as an environment variable, like so:
```
export EG_CERT_BUNDLE = "<path_to_custom_CA_Bundle>"
```
If the `EG_CERT_BUNDLE` environment variable is not set, the default behavior is implemented. This ensures backwards compatibility
Successfully initiates kernel post making the suggested changes:
_jeg.log_
```
20/09/24 13:52:31 INFO YarnClientImpl: Submitted application application_1598311220321_0081
20/09/24 13:52:31 INFO Client: Application report for application_1598311220321_0081 (state: ACCEPTED)
20/09/24 13:52:31 INFO Client:
client token: N/A
diagnostics: [Thu Sep 24 13:52:31 -0700 2020] …
```

Enabled supporting custom truststores for EG dispatch to SSL Enabled Yarn

---

enterprise_gateway/services/processproxies/container.py
enterprise_gateway/services/processproxies/processproxy.py

It was recently discovered that `KERNEL_IMAGE` did not flow from the client to be used during the kernel launch. Although this is a limited use case, as it requires the same image be used for a specific client regardless of the selected kernel, there are use cases where it makes sense (see #884).  This pull request makes the necessary changes such that a payload env of `KERNEL_IMAGE` will be used for that request's kernel launch.
The current definition of `KERNEL_IMAGE` is renamed to `EG_KERNEL_IMAGE` and has no default.  This env would be set if an administrator needed to use the same image across all kernel launch requests (again, very limited utility).  The precedence hierarchy, from lowest to highest, is as follows:
1. Use `EG_KERNEL_IMAGE`.
2. Use `image_name` from …

Flow KERNEL_IMAGE value for kernel launch

---

enterprise_gateway/services/processproxies/conductor.py
etc/kernelspecs/spark_python_conductor_cluster/bin/run.sh

Today the Conductor Proxy and all of JEG for Conductor must run through a Conductor EGO Service and be setup in a certain way. This new support allows for JEG to be run anywhere but offload workload to Conductor using JWT Tokens for authentication.

Add support for Conductor Proxy to work with JEG outside of Conductor Cluster

---

enterprise_gateway/services/processproxies/processproxy.py
etc/kernel-launchers/python/scripts/launch_ipykernel.py

In some environment pycryptodome is being used instead of pycryptodomex and can't be easily changed. This try/catch handles supporting using both pycryptdome and pycryptodomex.

Handle supporting using both pycryptdome and pycryptodomex

---

README.md

Randomly noticed that there's broken badge not showing proper version. Apparently due to typo in repo name on Pypi (or, if it was potentially renamed)

Fix badge for pypi in README

---

docs/source/kernel-kubernetes.md
etc/docker/docker-compose.yml
etc/docker/enterprise-gateway/start-enterprise-gateway.sh
etc/kubernetes/enterprise-gateway.yaml

to make `EG_KERNEL_WHITELIST` consistent with other environment variable lists such as `EG_ENV_PROCESS_WHITELIST`.
Currently `EG_ENV_PROCESS_WHITELIST` is just comma separated: 
`EG_ENV_PROCESS_WHITELIST=A,B,C`
While `EG_KERNEL_WHITELIST` is comma separated and surrounded by square brackets: 
`EG_KERNEL_WHITELIST=['docker_py','docker_r']`
This PR proposes to drop the brackers on `EG_KERNEL_WHITELIST`.
`EG_KERNEL_WHITELIST='docker_py','docker_r'`
I'm not an expert on bash environment variables and thus not sure whether this is the cleanest/safest way to add "[...]" brackets.
@kevin-bates suggested on Gitter to make a PR. Hopefully this can serve as a starting point for a PR, perhaps someone with more familiarity with the EG code base can check whether it's comprehensive. I used code search …

EG_KERNEL_WHITELIST: include brackets in start-enterprise-gateway.sh 

---

enterprise_gateway/services/sessions/kernelsessionmanager.py

The FileKernelSessionManager.load_session() method was not checking that persistence functionality was enabled, resulting in issues on more protected systems.  This adds the necessary enablement check that is already present in other methods.
Fixes #896

Protect load_session() functionality when persistence is disabled

---

docs/source/config-options.md
enterprise_gateway/mixins.py
enterprise_gateway/services/kernels/handlers.py
enterprise_gateway/tests/test_handlers.py

This change enables the ability to allow all envs specified in the kernel start request body to be passed to the kernel.  Previously only those envs specified in the KernelManager.env_whitelist were permitted (in addition to all those prefixed with `KERNEL_`).  With this change, setting `c.KernelManagert.env_whitelist = ['*']` or `EG_ENV_WHITELIST = "*"` will result in all envs specified in the request body _flowing_ to the kernel.  This will be helpful when parameterization becomes more prevalent.

Add ability to allow all envs in kernel request body

---

.github/workflows/build.yml
requirements.yml
setup.py

Remove python 3.5 from requirements, add 3.9

---

.github/workflows/build.yml
Makefile
enterprise_gateway/base/handlers.py
enterprise_gateway/enterprisegatewayapp.py
enterprise_gateway/services/api/handlers.py
enterprise_gateway/services/kernels/handlers.py
enterprise_gateway/services/kernels/remotemanager.py
enterprise_gateway/services/kernelspecs/handlers.py
enterprise_gateway/services/kernelspecs/kernelspec_cache.py
enterprise_gateway/services/processproxies/conductor.py
enterprise_gateway/services/processproxies/processproxy.py
enterprise_gateway/services/sessions/handlers.py
enterprise_gateway/tests/test_mixins.py
etc/docker/enterprise-gateway/Dockerfile
requirements.yml
setup.py

Changes necessary to move Enterprise Gateway's base from notebook to jupyter_server.

Use jupyter_server instead of notebook

---

etc/kernel-launchers/python/scripts/launch_ipykernel.py

Fix #951 
```python
>>> from random import random
>>> random.randint
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
AttributeError: 'builtin_function_or_method' object has no attribute 'randint'
>>> import random
>>> random.randint
<bound method Random.randint of <random.Random object at 0x7f830c00a020>>
```
Signed-off-by: cegao <cegao@tencent.com>

fix: Fix #951 about port range

---

docs/source/config-options.md
docs/source/contrib.md

Found a couple of broken links related to Jupyter doc refactoring.

Update broken links to Jupyter pages

---

enterprise_gateway/__init__.py
scripts/jupyter-enterprisegateway
setup.py

Fixes #960 by making the problem import lazy. Also removed redundant `"scripts"` field from `setup.py` (noticed that since I had to make a small tweak to both that and `"entry_points"`).
If making the `launch_instance` import lazy seems too convoluted, I think another valid fix would be to remove `launch_instance` from the module top-level entirely. It's sufficient to be able to do:
```python
from enterprise_gateway.enterprisegatewayapp import launch_instance
```

fixes #960: lazy import of launch_instance in top-level __init__.py

---

enterprise_gateway/services/kernelspecs/handlers.py

Add typing hints to the following file.
`enterprise_gateway/services/kernelspecs/handlers.py`
Fixes #849

#849 Add typing hints to kernelspec handler

---

docs/source/config-options.md
docs/source/getting-started-security.md
enterprise_gateway/services/processproxies/processproxy.py

This attempt to implement GSS as requested in #946.
I've tried to also document the other environment variable, though I
couldn't find where or how they are supposed to be used.
I'm also currently trying to find a deployment that could use GSS to
test this, but haven't so far.
I'm assuming that if GSS is enabled then it takes priority over
username/password.

Allow SSH authentication via GSS.

---

Makefile
enterprise_gateway/itests/test_python_kernel.py
enterprise_gateway/itests/test_r_kernel.py
enterprise_gateway/itests/test_scala_kernel.py
etc/docker/kernel-r/Dockerfile
etc/kernel-launchers/docker/scripts/launch_docker.py

The `enterprise-gateway-swarm.sh` script was removed in pull request #633 but we didn't catch its reference in the `itest-docker` tag in `Makefile` - which resulted in the following failure:
```
make itest-docker-prep
Error: No such service: itest-docker
make[1]: [itest-docker-prep] Error 1 (ignored)
Starting enterprise-gateway swarm service (run `docker service logs itest-docker` to see service log)...
/bin/bash: etc/docker/enterprise-gateway-swarm.sh: No such file or directory
make[1]: *** [itest-docker-prep] Error 127
make: *** [itest-docker] Error 2
```
These changes fix that issue and also address:
- an issue with conveying the network name, set at command launch
- the R kernel image (didn't have adequate packages - probably was an issue on k8s as well)
- the hostname wasn't being …

Changes necessary to get itest-docker passing

---

setup.py

Update WatchDog dependency version to avoid issues while installing other projects such as Elyra:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
jupyter-enterprise-gateway 2.5.0 requires watchdog==0.10.3, but you have watchdog 2.1.3 which is incompatible.
```

Update Watchdog dependency to version 2.1.3

---

Makefile

Without this, the `PYTHONPATH` environment variable is unset which leads to the error below.
```
(base) bgerrity@bgerrity-mbp enterprise_gateway % make dev
source activate enterprise-gateway-dev && python enterprise_gateway
Traceback (most recent call last):
File "/opt/miniconda3/envs/enterprise-gateway-dev/lib/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/opt/miniconda3/envs/enterprise-gateway-dev/lib/python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/Users/bgerrity/enterprise_gateway/enterprise_gateway/__main__.py", line 7, in <module>
import enterprise_gateway.enterprisegatewayapp as app
ModuleNotFoundError: No module named 'enterprise_gateway'
make: *** [dev] Error 1
(base) bgerrity@bgerrity-mbp …
```

Fix `make dev` to set `PYTHONPATH`

---

Makefile

I found that `make install` was broken when installing the tar file for EG due to conflicts with other tar files _now_ being built (well, these have existed for quite a while "now"). This adds better specifics for what files are installed via that target.

Fix Makefile install target

---

docs/source/config-options.md
enterprise_gateway/services/processproxies/processproxy.py

With Enterprise Gateway potentially coexisting with itself and/or remote provisioners (that utilize the same process-proxy framework) it would be a good idea to be able to tolerate port conflicts when the single response address port gets configured (on demand/first use).  This pull request uses logic similar to the various server startups that, when port retries are configured, will tolerate EADDRINUSE errors and retry a different port until a successful socket binding occurs or the retries are exhausted.
The default port number (as was the case when the single response address functionality was introduced) is `8877` and the default number of retries is `10`.  As with the other server startups, the first 5 retries attempt to bind to the next port sequentially, then, when the retry count …

Response port retries

---

enterprise_gateway/services/api/handlers.py

Add typing hints to the following file.
enterprise_gateway/services/api/handlers.py
Fixes #852

#852 Add typing hints to api handler

---

docs/source/config-options.md
enterprise_gateway/enterprisegatewayapp.py
enterprise_gateway/mixins.py
enterprise_gateway/tests/test_gatewayapp.py

Addressing #989: It's a fairly simple SSL check and doesn't offer any support for running without authentication. Not sure if this is the best approach; open to any feedback or alternative implementations.

Add origin restriction config

---

docs/source/system-architecture.md
enterprise_gateway/services/processproxies/crd.py
enterprise_gateway/services/processproxies/spark_operator.py
etc/kernel-launchers/kubernetes/scripts/launch_custom_resource.py
etc/kernel-launchers/kubernetes/scripts/sparkoperator.k8s.io-v1beta2.yaml.j2
etc/kernelspecs/spark_python_operator/kernel.json
etc/kubernetes/enterprise-gateway.yaml

eg now has supported raw pod based k8s process proxy but maybe not so appropriate i wanna use some integrated k8s operator including some custom resources.
this PR implement a new process proxy, which makes it easy to define some kernel based on a certain k8s custom resource, such as spark application inside gcp spark operator. 
Resolves #984

add crd process proxy to support some crd based k8s application like spark operator

---

docs/source/kernel-kubernetes.md
etc/docker/kernel-image-puller/Dockerfile
etc/docker/kernel-image-puller/kernel_image_puller.py
etc/kubernetes/helm/enterprise-gateway/Chart.yaml
etc/kubernetes/helm/enterprise-gateway/templates/daemonset.yaml
etc/kubernetes/helm/enterprise-gateway/values.yaml

PR #995 was introduced to better tolerate installations configured with a non-docker container runtime.  This PR introduces the use of `crictl` (Containerd's CLI tool) to check image existence and pull images when a docker runtime is not configured.
Since `crictl` needs to mount the container runtime socket (to accomplish docker-in-docker, or rather, container-in-container) this change makes that socket reference a configurable value in the helm chart.
If a CRI socket is configured that is not detected as Docker or Containerd, KIP will proceed with attempting image management using `crictl` since it can take a _runtime endpoint_ that is composable from the mounted socket value.  That said, there's a good chance that another runtime may introduce issues, but I'm hoping this PR introduces …

KIP: Add support for containerd-based installations

---

enterprise_gateway/tests/test_handlers.py
etc/docker/enterprise-gateway/Dockerfile
etc/docker/kernel-py/Dockerfile
etc/docker/kernel-r/Dockerfile
etc/docker/kernel-tf-gpu-py/Dockerfile
etc/docker/kernel-tf-py/Dockerfile
etc/kernelspecs/dask_python_yarn_remote/kernel.json
etc/kernelspecs/python_distributed/kernel.json
etc/kernelspecs/python_docker/kernel.json
etc/kernelspecs/python_kubernetes/kernel.json
etc/kernelspecs/python_tf_docker/kernel.json
etc/kernelspecs/python_tf_gpu_docker/kernel.json
etc/kernelspecs/python_tf_gpu_kubernetes/kernel.json
etc/kernelspecs/python_tf_kubernetes/kernel.json
etc/kernelspecs/spark_python_conductor_cluster/kernel.json
etc/kernelspecs/spark_python_kubernetes/kernel.json
etc/kernelspecs/spark_python_yarn_client/kernel.json
etc/kernelspecs/spark_python_yarn_cluster/kernel.json
etc/kubernetes/helm/enterprise-gateway/templates/deployment.yaml
etc/kubernetes/helm/enterprise-gateway/values.yaml

Kernel-debugger enablement - which starts here: #980 .
And I add pvc options to mount kernelspecs, I guess It's simpler than nfs.

Enable debugger for python-related kernelspecs and add option to mount kernelspecs with pvc

---

etc/docker/enterprise-gateway/Dockerfile
etc/docker/kernel-py/Dockerfile
etc/docker/kernel-r/Dockerfile
etc/docker/kernel-tf-py/Dockerfile

After building new images in preparation for a 2.6.0, it was found that the ipykernel installed in python-kernel images did not include debugger support as it was installed from the conda defaults channel.  This caused the work done in #986 to appear as though debug was not available, when, in reality, the issue was with the docker image.
Instead, we should update the base jupyter images and NOT install jupyter packages over those, but use the packages in the base container.
I have confirmed that python debugger support is enabled with these changes and these will be part of the 2.6.0 release.
I've also found that the base images support date-based tags and all jupyter-derived images have been updated to use the builds tagged `2022-01-24`.  This will make it easier to locate the relative …

Update base jupyter images, use their jupyter packages

---

etc/docker/kernel-py/Dockerfile
etc/docker/kernel-py/README.md
etc/docker/kernel-r/Dockerfile
etc/docker/kernel-spark-py/README.md
etc/docker/kernel-tf-gpu-py/Dockerfile
etc/docker/kernel-tf-gpu-py/README.md
etc/docker/kernel-tf-py/README.md

After creating and running images with the #986 and (then) #1029 PRs while preparing for the EG 2.6.0 release, several issues were discovered, mostly related to python, spark, and R versions.  In addition, the tensorflow-gpu image was also using an older version of `ipykernel`.
This PR essentially reverts the jupyter docker-stack base images for kernel-py and kernel-r, upon which their corresponding spark-based images are derived.  It also updates the version of tensorflow for the GPU image from 2.4.0 to 2.7.0.  Note that the version of tensorflow for the regular image (derived from jupyter/tensorflow-notebook) is using tensorflow 2.6.2.
Some of the README files that are posted on dockerhub have also been updated where appropriate.
One thing learned from this exercise is that PySpark on …

Validate images relative to python, spark, and debugger

---

etc/Makefile
etc/kernel-launchers/kubernetes/scripts/launch_custom_resource.py
etc/kernel-launchers/kubernetes/scripts/launch_kubernetes.py
etc/kernel-launchers/kubernetes/scripts/sparkoperator.k8s.io-v1beta2.yaml.j2
etc/kubernetes/enterprise-gateway.yaml

This adds the Spark Operator to K8s kernespecs package, updates the spark operator parameters to follow the new EG/Jupyter Client pattern, and fixes in the proxy to be able to run and submit jobs via it

Spark operator k8s updates to enable it in gateway on k8s

---

release.sh

It would be helpful to build the docker images during the release build.  These will be pushed if the release is not in "dryRun", otherwise they remain on the local system.  Previously, it was not sufficient to build the images from the release working directory because, after the release script has run, the dev versions are in place and extra care was required to get the proper kernelspecs included, etc.
The script also "captures" the `build` and `dist` trees to the version-specific directory.  This will more easily enable troubleshooting and "adjustments" to build artifacts (if necessary).

Build images during release, capture release build/dist dirs

---

docs/environment.yml
readthedocs.yml

The RTD builds were breaking with the merge of https://github.com/jupyter/enterprise_gateway/pull/1034 due to the Python 3.9 reference: https://readthedocs.org/projects/jupyter-enterprise-gateway/builds/15945185/
This PR reverts the Python version to 3.8 for the time being.  We can revisit later (when the docs are reformatted).

Revert the RTD python version to 3.8

---

docs/source/conf.py
readthedocs.yml

An additional (and hopefully last) PR to fix the RTD build.  We got further with #1035, but this PR removes the reference to IPython highlighting extension. This reference was "inherited" from the jupyter_server config, but EG doesn't use it (that I know of).

Fix RTD - remove IPython highlighting reference

---

etc/Makefile

Turns out our build has been broken since December of 2020!  The issue is that, at that time, we introduced the `SA` macro on the command line to indicate the `source activate` command to use when switching into the conda env used by the make targets and properly declared that macro in the primary `Makefile` as:
```
SA?=source activate
```
The problem occurs when building the `enterprise-gateway-demo` image.  In that case, the upper `Makefile` invokes the `etc/Makefile` which then needs to invoke a target back in the parent `Makefile`.  Since the `etc/Makefile` defined `SA` as:
```
SA:=source activate
```
the command line version gets unset and the command invoked in the parent Makefile fails with:
```
make[3]: Entering directory '/home/runner/work/enterprise_gateway/enterprise_gateway' …
```

Fix build to propagate SA macro between makefiles

---

docs/source/index.rst
docs/source/users/index.rst

Just discovered that references meant to link to the `Operators Guide` (`operators/index.rst`) were hitting the Python operators documentation, presumably because I didn't have a reference to `name: operators` in the `index.rst`.  Since other links to various "role" `index.rst` were also a little funky relative to where the link placed the focus, I updated those as well.

Fix operator references that were directing to Python docs

---

etc/docker/enterprise-gateway/README.md
etc/docker/kernel-spark-py/README.md
etc/docker/kernel-spark-r/README.md
etc/docker/kernel-tf-gpu-py/README.md
etc/docker/kernel-tf-py/README.md

When applying the changes from #1049 to the dockerhub image README descriptions, Grammarly reported on some (very minor) issues that I felt should just be handled.  Mostly its a double-space issue, but there was a typo it also found.

Fix up some docker image README issues (minor)

---

enterprise_gateway/services/kernelspecs/kernelspec_cache.py
setup.py

The EG integration tests have been timing out waiting for EG to start.  It turns out this was due to a recent change to `markupsafe` which removed a method used by older versions of `jinja2`.  Since the `elyra/demo-base:2.4.6` image has `jinja2==2.11.2` installed and EG required `>=2.10`, a newer version of Jinja2 was not installed, producing this issue when EG goes to start...
```
Waiting for enterprise-gateway to start...
2022-04-04T18:16:08.380142789Z     from jinja2 import Environment, FileSystemLoader
2022-04-04T18:16:08.380146289Z   File "/opt/conda/lib/python3.7/site-packages/jinja2/__init__.py", line 12, in <module>
2022-04-04T18:16:08.380162289Z     from .environment import Environment
2022-04-04T18:16:08.380166389Z   File …
```

Bump jinja2 dependency floor

---

enterprise_gateway/mixins.py
enterprise_gateway/services/kernels/remotemanager.py
enterprise_gateway/services/processproxies/distributed.py

Add a kernel opening mechanism for load balancing.Turn on at the node with the least number of kernels.
We can use load balancing by setting the variable c.enterprisegatewayapp.load_balance = True.
If you want to start the kernel by specifying a node, you can specify it by using KERNEL_REMOTE_HOST in the variable env.
Resolves: #1062

Add a kernel opening mechanism for load balancing!

---

docs/source/operators/config-cli.md
docs/source/operators/deploy-distributed.md
docs/source/users/kernel-envs.md
enterprise_gateway/mixins.py

This pull request adds the documentation relative to the load-balancing algorithm added as part of #1068.  It essentially adds entries in the Operators Guide in the Command-line options, and Distributed deployments sections.
@LeeMoonCh - I would appreciate your review of this PR.  Thank you.

Add doc entry for load-balancing algorithm configuration

---

.pre-commit-config.yaml
docs/source/developers/kernel-launcher.md
docs/source/developers/kernel-specification.md
etc/kernel-launchers/python/scripts/launch_ipykernel.py

Issues #795 and #1060 both warranted the need to not use `embed_kernel()` when starting a python-based kernel.  `embed_kernel()` was the original approach used to launch the `ipykernel` from our launcher, since we wanted to control the SparkContext variables, but it turns out (at least in my initial testing) that that was not necessary.
This change uses the inspiration from the respective issues (and their authors @lazywhite and @jaybubs, respectively) to address both the startup script issue from #1060 as well as add support for ipykernel derivations like `MatlabKernel` in #795.
We also should try to support older python versions in the launcher, so I reverted the use of `f-strings` for now (as my YARN systems are using older versions of Python).
I installed a startup profile on my test …

Support startup scripts and ipykernel subclasses

---

.github/workflows/build.yml
Makefile
docs/Makefile
docs/source/contributors/devinstall.md
setup.py

This pull request removes the use of a conda env from the EG build workflow (primarily in the Makefile).  This simplifies the working environment and appears to trim 3 minutes from each of the python-versioned CI jobs.
While doing this, I found that the former `make install` target was more like a test-install target, so I named it as such and split the two forms of installation it was performing into separate targets (so we can make use of one from our CI actions).
I also noticed that `make dev` was merely running whatever EG was installed, so I updated the target name to `run-dev` and had it depend on an actual build of EG to make it more inclusive.
The docs `Makefile` was also updated because the check for `sphinx-build` was interfering with the ability to install requirements using …

Remove conda env config from build workflow

---

enterprise_gateway/services/processproxies/processproxy.py
pyproject.toml

The [paramiko](https://github.com/paramiko/paramiko) package uses the [cyrptography]() package that, as of a couple of days ago, has released a new major version (37.0.0).  This version removes the `blowfish` cipher algorithm.  However, since `paramiko` maintains a static list of algorithms and that list includes `blowfish`, a `cryptography.utils.CryptographyDeprecationWarning: Blowfish has been deprecated` warning message is produced when loading the `paramiko` library.
Because `pytest` treats deprecation warnings as errors (not sure if this is by default or what), the unit tests fail...
```
ERROR enterprise_gateway/tests/test_enterprise_gateway.py - cryptography.utils.CryptographyDeprecationWarning: Blowfish has been deprecated
ERROR enterprise_gateway/tests/test_enterprise_gateway.py - …
```

Ignore deprecation warning from paramiko during pytest execution

---

enterprise_gateway/services/processproxies/k8s.py

Whilst deleting a kernel namespace returns a v1.Status, deleting a Pod
will return a v1.Pod and its status field is a v1.PodStatus, not a
string.
The existing code currently raises an exception as it attempts to do an
'in' check against the V1PodStatus type rather than a string as it
expected. This is logged as:
> Error occurred deleting pod: argument of type 'V1PodStatus' is not iterable

fix(k8s): handle status of deleted Pod correctly

---

docs/source/operators/config-env-debug.md
enterprise_gateway/services/kernels/remotemanager.py
enterprise_gateway/services/processproxies/container.py

This PR is raised wrt the fix proposed in #1051  to wait on the Kernel Shutdown request until the kernel Restart is completed. 
- the fix is made only on EG as it depends on the Kernel field set with in the EG code only: [kernel.restarting](https://github.com/jupyter-server/enterprise_gateway/blob/master/enterprise_gateway/services/kernels/remotemanager.py#L488)
-  There are some TODOs and open items which are open for discussion. (done)
- The time used to wait for restart to complete is inherited / taken from "KERNEL_LAUNCH_TIMEOUT" as this is precisely the time which even the kernel start would wait before giving up on the kernel.  
- As we are waiting on the restart to complete and no going to allow shutdown to happen in parallel, the chances of Shutdown flow terminating the kernel at …

Attempt to fix FD leak issue #1051

---

.github/workflows/build.yml
pyproject.toml
release.sh

Hatch is newly added pypa backend with more flexibility, and helps avoid https://github.com/pypa/pip/issues/11110, which is breaking builds.
Tbump is useful for keeping versions in sync across files.  We use in in Jupyter Releaser.

Use hatch and tbump

---

pyproject.toml

Now that an updated release of `paramiko` is available, the [temporary change](https://github.com/jupyter-server/enterprise_gateway/pull/1081) to ignore deprecation warnings due to the removal of `Blowfish` from the `Cryptography` package can now be removed.
This pull request bumps the floor version of `paramiko` to `2.11` and removes the entry to ignore the aforementioned deprecation warning.

Bump paramiko version, remove temp ignore of deprecation warning

---

docs/source/users/kernel-envs.md
etc/kernel-launchers/operators/scripts/sparkoperator.k8s.io-v1beta2.yaml.j2

Originates from necro-bumped thread #523 (https://github.com/jupyter-server/enterprise_gateway/issues/523#issuecomment-1126131413).
cc @kevin-bates I haven't had the time to test it >yet<. I will test everything on Sunday/Monday and report back. 😃

Add env var to specify a spark k8s operator configMap

---

.github/workflows/build.yml
Makefile
docs/source/contributors/devinstall.md

Per #1098, I am reintroducing some of the conda env pieces to assist with locally running EG and with debugging using an IDE. I specifically brought the targets for making and activating the conda environment but did not add that back to all of the other steps as it remains unnecessary for them. 
I also updated the Contributor docs to reflect the additional step that can be used to aid local development
Resolves: #1098

reintroduce conda env setup and docs

---

docs/source/operators/config-cli.md
docs/source/operators/config-kernel-persistence.md
docs/source/operators/index.rst
enterprise_gateway/enterprisegatewayapp.py
enterprise_gateway/services/sessions/kernelsessionmanager.py

Added a new way to persist kernels to any database. You must create an API to interact with your database. The API should have 4 endpoints:
- 1 DELETE that will delete all kernel sessions from a list of kernel ids
- 1 POST that will take kernel id as a path variable and kernel session in body and save it to a database
- 1 GET that will take the kernel id as a path variable and retrieve that information from a database
- 1 GET that will retrieve a list of all kernel sessions from a database
In order to setup the WebhookKernelSessionManager, you must set `--EnterpriseGatewayApp.kernel_session_manager_class` to `enterprise_gateway.services.sessions.kernelsessionmanager.WebhookKernelSessionManager`, `--WebhookKernelSessionManager.webhook_url` to the endpoint url of your API and …

Added new WebhookKernelSessionManager for Kernel Persistence

---

Makefile
docs/source/contributors/devinstall.md

As per the current example, the syntax shared for running selective UT is: 
`make test TEST="test_gatewayapp::TestGatewayAppConfig" ` which does not work as expected and throws `ERROR: file or directory not found: enterprise_gateway/tests/test_gatewayapp::TestGatewayAppConfig` Exception.
```
make test TEST="test_gatewayapp::TestGatewayAppConfig"                        
pytest -vv  enterprise_gateway/tests/test_gatewayapp::TestGatewayAppConfig
============================================================== test session starts ==============================================================
platform darwin -- Python 3.8.5, pytest-7.1.2, pluggy-1.0.0 -- /Users/rhgoyal/miniconda3/envs/eg-ut/bin/python3
cachedir: .pytest_cache
rootdir: /Users/rhgoyal/learning/jupyter-project/enterprise_gateway, …
```

Typo in make file example for running UTs

---

docs/doc-requirements.txt
requirements.yml

When attempting to run the newly re-added `make env` target, environment creation was failing citing "`Directory '..' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.`". The directory in `requirements.yml` is updated here (to `.`) to point to the correct location for doc dependency installation.
After this change was made, another error was raised (below) where conda was unable to resolve the project requirement for `jinja2>=3.1` (from `pyproject.toml`) with the doc requirement for `jinja2<3.1`.
```
The conflict is caused by:
The user requested jinja2<3.1
jupyter-enterprise-gateway 3.0.0.dev0 depends on jinja2>=3.1
```
The jinja cap in `doc-requirements.txt` (in place due to https://github.com/sphinx-doc/sphinx/issues/10291) is removed here as the cited issue no longer …

Update dependency requirements to support `make env` target

---

Makefile
requirements.yml
update-demo-base.sh

The build wasn't working in clean environments
unless you had manually installed pre-commit dependency.

Install pre-commit as part of the lint make task

---

enterprise_gateway/enterprisegatewayapp.py

In our logs, it happened to get a `raise web.HTTPError(404, u'Kernel does not exist: %s' % kernel_id)` exception in enterprisegatewayapp.shutdown, thus the cleanup being compromised.
Since this function is more a cleanup function, it shouldn't fail and cleanup as much as possible instead. Otherwise, kernels pods may leak.
The "Shut down complete" log is useful to see if termination grace period is enough and EG is not being killed.

Make EnterpriseGatewayApp.shutdown more robust, since it's a cleanup procedure

---

etc/kubernetes/helm/enterprise-gateway/templates/eg-clusterrole.yaml

When integrating EG with Spark Operator, the EG service account
needs to be able to create/schedule "sparkapplications" and thus
require the additional permissions.

Enable EG to create pods via CRDs on Spark Operator

---

enterprise_gateway/services/processproxies/processproxy.py
etc/kernel-launchers/python/scripts/launch_ipykernel.py
etc/kernelspecs/spark_R_conductor_cluster/kernel.json
etc/kernelspecs/spark_R_yarn_cluster/kernel.json
etc/kernelspecs/spark_python_conductor_cluster/kernel.json
etc/kernelspecs/spark_python_yarn_cluster/kernel.json
etc/kernelspecs/spark_scala_conductor_cluster/kernel.json
etc/kernelspecs/spark_scala_yarn_cluster/kernel.json

While investigating #1116 several issues were identified, primarily relative to interaction with YARN.
1. It was found that an exception was occurring as the Python kernel launcher was terminating.  The suspicion is that this delay lead to the scenario seen in #1116 where, ultimately, the YARN Resource Manager was restarting the launcher while the application was being shut down (and ultimately is shut down).  
2. A similar auto-restart-issue was seen using the Scala kernel but since its launcher wasn't encountering an exception, this was the information needed to conclude that indeed a race condition was occurring between the time the listener/launcher terminates and the time the YARN resource manager shuts down the application (in cluster mode).
3. A couple of the messages surrounding …

Fix shutdown issues

---

etc/docker/kernel-tf-gpu-py/Dockerfile

Attempts to build the tensorflow GPU kernel image using `make kernel-tf-gpu-py` fail with the following:
```
...
#6 4.860 W: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
#6 4.860 E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease' is no longer signed.
------
executor failed running [/bin/bash -c apt-get update && apt-get install -yq     build-essential     libsm6     libxext-dev     libxrender1     netcat     python3-dev     tzdata     unzip &&     rm -rf /var/lib/apt/lists/* &&     pip install --upgrade future pycryptodomex ipykernel]: exit code: 100
make[1]: *** …
```

Update tensorflow-gpu base image

---

etc/docker/kernel-image-puller/kernel_image_puller.py

The changes in #1090 inadvertently changed the datatype of `pulled_images` from a `set` to a `list` in the Kernel Image Puller (KIP).  This lead to the following issues for each image pulled (which caused KIP to pull all images on every iteration 3 times):
```
[I 2022-06-29 17:30:17,824 kernel_image_puller.t2] Pulled image 'elyra/kernel-r:kb0' in 1.127 secs.
[W 2022-06-29 17:30:17,824 kernel_image_puller.t2] Attempt 1 to pull image 'elyra/kernel-r:kb0' encountered exception - retrying.  Exception was: 'list' object has no attribute 'add'.
[I 2022-06-29 17:30:17,824 kernel_image_puller.t2] Pulling image 'elyra/kernel-r:kb0'...
[I 2022-06-29 17:30:18,959 kernel_image_puller.t2] Pulled image 'elyra/kernel-r:kb0' in 1.135 secs.
[W 2022-06-29 17:30:18,959 kernel_image_puller.t2] Attempt 2 to …
```

KIP: Define pulled_images as set, not list

---

etc/kubernetes/helm/enterprise-gateway/values.yaml

Per the discussion starting [here](https://github.com/jupyter-server/enterprise_gateway/pull/1073#issuecomment-1175329542), we should disable the default to create a `PodSecurityPolicy` in the Kernel Image Puller.  I've also included a comment indicating the applicable versions/timeframe, along with a suggestion for how an operator would need to proceed if using a version of K8s in which PSPs don't exist.
The table of [K8s/Helm options in the Operators Guide](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/operators/deploy-kubernetes.html#helm-configuration-parameters), already show the default as `false`. :+1:
Thanks to @darkstarmv for their helpful information.

Switch default to create PSP in KIP to false due to deprecation

---

etc/kernel-launchers/python/scripts/launch_ipykernel.py

This PR fixes the issue #1112.
Removed the previous commit and PR(#1114) as we are using the new logic suggested by @kevin-bates.
Testing:
1. Started a PySpark kernel with the changes.
2. Started kernels and executed code followed by interrupting the same. Verified job gets killed in Spark Logs and also we can start executing other cells.
3. Ran jobs in threads and verified all running jobs were killed.

Changes for handling interrupts for PySpark Kubernetes Kernel

---

enterprise_gateway/base/handlers.py
enterprise_gateway/enterprisegatewayapp.py
enterprise_gateway/mixins.py
enterprise_gateway/services/api/handlers.py
enterprise_gateway/services/kernels/handlers.py
enterprise_gateway/services/sessions/handlers.py

Fixes #853
Most of these type hint changes are pretty straightforward. The only change beyond simple type hints is that I had to change the import alias of the `List` and `Set` traitlets, as they conflicted with the `List` and `Set` typing hint classes. The former have been re-aliased to `ListTrait` and `SetTrait`.

Add type hints to EG application

---

docs/doc-requirements.txt
docs/source/_static/custom.css
docs/source/conf.py
docs/source/contributors/index.rst
docs/source/contributors/sequence-diagrams.md

Inspired by the work @telamonian started on #1039 and given that a reasonable workaround has been identified for the [`sphinxcontrib-mermaid` issue](https://github.com/jupyter-server/enterprise_gateway/pull/1039#issuecomment-1044798410), I've gone ahead and incorporated Max's kernel-init-sequence diagram into a "Sequence Diagrams" section of the Contributors guide using the `mermaid` markdown approach.   The hope is that other diagrams will be contributed downstream.  We can also choose to relocate this diagram as we see fit.
Special thanks to @telamonian for getting this ball rolling. 
Here's a screenshot consisting of a portion of the diagram and surrounding area:
Co-authored-by: telamonian <telamonian@users.noreply.github.com>

Add kernel launch sequence diagram to contributors guide

---

Makefile

During release build prep, I found an issue where a previous PR contained an inadvertent change to the `WHEEL_FILES` macro in the Makefile.  This PR reverts that change and extends the macro to also ignore any directories named `__pycache__`.
Without this change, the following issue would occur:
```
make clean dist test
make clean dist
make: *** No rule to make target `enterprise_gateway/tests/__pycache__/__init__.cpython-39.pyc', needed by `dist/jupyter_enterprise_gateway-3.0.0.dev0-py3-none-any.whl'.  Stop.
```
That is, the second cycle of `make clean dist` after performing a test would pickup a `.pvc` file in the `WHEEL_FILES` macro, leading to the issue - despite the fact that the `clean` target explicitly removes `__pycache__` directories.  I suspect that the `lint` step of `make …

Fix Makefile WHEEL_FILES list

---

release.sh

We removed the need for `etc/kubernetes/enterprise-gateway.yaml` but forgot to remove its reference from the release script in https://github.com/jupyter-server/enterprise_gateway/pull/1123.

Remove reference to eg yaml that no longer exists

---

etc/docker/kernel-image-puller/kernel_image_puller.py
etc/kubernetes/helm/enterprise-gateway/templates/daemonset.yaml

Prior to these changes, the Kernel Image Puller would unconditionally pull images on its first pass when the policy was `IfNotPresent` despite the fact that applicable images are locally present.  This prevented the ability to use locally-defined images - which is useful in dev environments, but also in environments in which you wish "pre-seed" images.
There are two areas of change.
1. The KIP has been updated to check for image existence even when the image has yet to be pulled (i.e., the first-time scenario).  If the image exists, it considers it pulled and adds it to KIP's pulled-images set.  KIP will continue to monitor the images, just as it does today.
2. The helm chart has been modified to tolerate a missing `Values.kip.defaultContainerRegistry` value in which case the …

Use local kernel images if they exist

---

enterprise_gateway/services/processproxies/container.py
enterprise_gateway/services/processproxies/k8s.py

This pull request attempts to address the delay seen when shutting down k8s-managed kernels.  I believe the issue is because the pod (and namespace if not BYO namespace) is not terminated when the kernel process has stopped.  Previously, the pod/namespace is not deleted until the cleanup phase, but these changes move the container resource termination to when the listener is shut down.  This allows the polling to check that the "kernel" has terminated to leverage the container status, which, previously, because it had yet to occur, was causing the fallback termination behavior to occur.
I suspect this was not a problem in older versions of kubernetes because (just a hunch) when the container's process terminated the container terminated.  However, I suspect k8s has "grown" enough where …

Address delayed shutdown behavior in k8s kernels

---

enterprise_gateway/services/sessions/kernelsessionmanager.py

In `load_sessions()`, we need to traverse an iterable list `kernel_sessions` to get `kernel_session` . However if we retrieve the response with `response.content`, it actually give us back byte string, and leads to iterate on byte char instead of a dict object. Therefore, this PR address the improper used `content` to `json()` and rm the `json.loads()` part in `_load_session_from_response`
[Test Plan]
Having a customized WebhookKernelSessionManager deploy on Kubernetes and works properly with these changes.

Ensure kernel session retrieve from resp is correct type

---

docs/source/operators/deploy-distributed.md

During preparation for building the 3.0.0 beta release, I found a malformed link that referenced `v2.5.0` instead of `v2.6.0`.  Without this update, that link will not be altered to reference `v3.0.0` resources via the `release.sh` script.

Update v2.6.0 tar file reference

---

docs/source/developers/rest-api.rst

Added a `/` to the route in the Kernel Interrupt section to correct the API path

small API path correction

---

docs/source/developers/kernel-library.md
docs/source/developers/kernel-manager.md

fix https://github.com/jupyter-server/enterprise_gateway/issues/978 
We need to pass the `kernel_name` as argument explicitly since setting it in the `NotebookClient` constructor time doesn't really propagate down to `GatewayKernelManager`

Update kernel manager library docs

---

enterprise_gateway/services/processproxies/crd.py

Fixes #1167
This PR includes the changes suggested in https://github.com/jupyter-server/enterprise_gateway/issues/1167#issuecomment-1267584529 
- renamed `kill()` to `terminate_container_resources()`
- pull logic in `terminate_custom_resources()` into the appropriate place in `terminate_container_resources()`
Prior to these changes, the spark operator pods lingered without being terminated on kernel change despite the pod logs indicating that the shutdown signal as received.
```
[I 2022-10-19 16:01:07,027.027 launch_ipykernel] server_listener got request: {'signum': 2}
[I 2022-10-19 16:01:07,028.028 launch_ipykernel] server_listener got request: {'shutdown': 1}
```
Now, pods are deleted on kernel change as expected. @vivekbhide also confirmed as such in …

Rename CRD kill method and incorporate terminate_custom_resources

---

Makefile
docs/source/operators/deploy-kubernetes.md
etc/kubernetes/helm/enterprise-gateway/Chart.yaml
release.sh

The helm version (whose format differs from that of the release version format) was not being handled correctly via the `release.sh` script.  This pull request addresses that by recognizing hyphens.
In addition, the asset produced by `make helm-chart` (actually via the `helm package`) command, does not follow the same naming convention as that of the other assets we include.  This PR renames the file to that of the other assets (and actually closer to what we originally documented - whose suffix is updated in this PR as well).
Fixes: #1177

Fix helm version handling and package naming

---

docs/source/operators/deploy-kubernetes.md

While troubleshooting an issue, I discovered the example `helm install` command was not correct in that the first occurrence of `[VERSION]` in the example should be prefixed with `v` because it represents the tag name.  This pull request fixes the example.

Fix version portion of download command to refer to tag name

---

etc/kernel-launchers/kubernetes/scripts/launch_kubernetes.py

Problem Statement
---
We need to create service and configmap per kernel pod for launch spark driver without cluster mode (because we cannot use SparkContext to add jars.package option and other things)
Feature Description
---
The PR allow add kind service and configmap in kernel-pod.yaml.j2 and add ownerReference to kernel pod in new object (usefull when delete kernel)
Delete all namespace can resolv the problèm but we prefer not to keep a ghost object
Exemple kernel-pod.yaml : 
```
<default pod template>
---
apiVersion: v1
kind: Service
metadata:
name: svc-{{ kernel_pod_name }}
namespace: "{{ kernel_namespace }}"
labels:
kernel_id: "{{ kernel_id }}"
app: enterprise-gateway
component: kernel
source: kernel-pod.yaml
spec:
selector:
app: enterprise-gateway
component: kernel
kernel_id: "{{ …
```

[feature] add support for manage service and configmap in kernel-pod

---

etc/kernel-launchers/bootstrap/bootstrap-kernel.sh
etc/kernel-launchers/docker/scripts/launch_docker.py
etc/kernel-launchers/kubernetes/scripts/launch_kubernetes.py

This pull request updates the container-based launchers (kubernetes, docker) and the `bootstrap-kernel.sh` script used in the kernel images to recognize and flow `--kernel-class-name` values to the python launcher.
When set, python-based kernel containers will have a `KERNEL_CLASS_NAME` env value corresponding to the configured kernel class that is set in the `kernel.json` via `--kernel-class-name`.
Since our kernelspecs don't set this value, a good way to test is to exec into the EG pod/container and add 
```
"--kernel-class-name",
"ipykernel.ipkernel.IPythonKernel"
```
to the `argv` stanza, then confirm the environment values from within the launcher kernel.
Resolves #1184

Flow kernel-class-name to kernel container if specified in kernel specification

---

etc/docker/kernel-image-puller/kernel_image_puller.py

While working with the [Remove Provisioners](https://github.com/gateway-experiments/remote_provisioners), I found that the Kernel Image Puller (KIP) was not pre-pulling images configured for provisioners.  Since their kernel spec configurations are nearly identical wrt how images are defined (process proxies use a `process_proxy` stanza while provisioners use a `kernel_provisioner` stanza), it's trivial for KIP to support both.  
This PR adds code to attempt to access the `kernel_provisioner` stanza when the `process_proxy` stanza is not found in a given kernel spec.

Allow KIP to pull images relative to kernel provisioners

---

etc/kernel-launchers/kubernetes/scripts/launch_kubernetes.py

I am not entirely sure this is the best way to go, as well as I am aware we should keep the original script minimal to encourage downstream customizations. 
However, I find it confusing when out of the box, with the default kernel-pod.yaml.j2 (and kernel_volume enabled), we cannot have idempotency and jupyter EG will just return error because given the same kernel id, the same pod and pvc cannot be connected from the client side. 
This pull request shows my little adjustments to improve that. And while of course it can be applied to other resources, I would propose just keep it as minimal as possible and PVC as well as pod proves to be great targets (they can also be cleaned up by terminate_container_resources inside k8s.py process proxy)

Handle the case when pod and/or pvc has already been created

---

release.sh

When performing a dry run for the 3.1.0 release, I found that the multi-arch image builds took way too long.  Instead, I think it would be better to build the images in a non-multi-arch fashion so those images can first be tested prior to their push to dockerHub.  This essentially implies that multi-arch builds will occur AFTER a release.  That said, I did leave multi-arch image builds enabled for the non-dry-run builds.

Don't perform multi-arch image builds on dry runs

---

etc/docker/kernel-py/Dockerfile
etc/docker/kernel-r/Dockerfile

Just prior to cutting the release I noticed that the python used in some of the kernel images was 3.7.  This pull request bumps the python version to 3.9.7 by updating the corresponding docker-stacks tag values.  Since this tag was already in use by the `enterprise-gateway` and `kernel-tf-py` only `kernel-py` and `kenrel-r` base images have been updated to help minimize changes at this stage in the "release" cycle.

Update python version, make docker-stacks tags consistent

---

.github/dependabot.yml
.github/workflows/build.yml
.pre-commit-config.yaml
Makefile
docs/source/conf.py
enterprise_gateway/client/gateway_client.py
enterprise_gateway/enterprisegatewayapp.py
enterprise_gateway/mixins.py
enterprise_gateway/services/kernels/remotemanager.py
enterprise_gateway/services/kernelspecs/handlers.py
enterprise_gateway/services/processproxies/conductor.py
enterprise_gateway/services/processproxies/processproxy.py
enterprise_gateway/services/sessions/kernelsessionmanager.py
enterprise_gateway/services/sessions/sessionmanager.py
enterprise_gateway/tests/test_handlers.py
enterprise_gateway/tests/test_mixins.py
etc/docker/kernel-image-puller/kernel_image_puller.py
etc/kernel-launchers/R/scripts/server_listener.py
etc/kernel-launchers/docker/scripts/launch_docker.py
etc/kernel-launchers/python/scripts/launch_ipykernel.py
pyproject.toml

Adopt ruff, which is faster and replaces flake8, isort, and pyupgrade
Move linters from pre-commit to Makefile
Add pip to dependabot
Address typings which were not being checked by pre-commit...

Adopt ruff and address lint

---

etc/docker/kernel-spark-py/Dockerfile
etc/docker/kernel-spark-r/Dockerfile

Apparently, the "last minute" change made in #1207 for 3.1.0 came back to bite me!  Those base images do not include `/opt/conda/bin/tini` which we preferred over the default `/usr/bin/tini`.  As a result, the adjustments we make in our spark images that derive from the images built from those _docker-stacks_ images were DOA.  (What could possibly go wrong, right? :smile:)
This pull request removes the use of `/opt/conda/bin/tini` and merely performs the previous adjustment of `-s` to `-g` relative to `/usr/bin/tini`.
Fixes: #1216

Fix kernel-spark-py and kernel-spark-r images

---

Makefile
etc/Makefile

This pull is pretty simple, it adds a TARGET_ARCH variable to makefile and enable users to do something like:
```bash
make enterprise-gateway TARGET_ARCH='linux/amd64'
```
With the growing number of client machines like macbook m1, this can help users who do not want to build for multiple architecture but still can specify their desired architecture to work perfectly without having to change the source code. I have run into situation where docker build on macbook would just build an ARM version so the cloud linux amd 64 machine cannot run the executable file. 
---

Support building image with dedicated platform by specifying compatible docker flags

---

etc/docker/enterprise-gateway-demo/start-enterprise-gateway.sh.template

I suspect the [change to not unconditionally inherit the value of env `PATH`](https://github.com/jupyter-server/enterprise_gateway/pull/1225) has side-affected the CI test `test_r_kernel.py::TestRKernelClient` because it can no longer find the `python` command (based on troubleshooting the issue).
Rather than flow `PATH` via the `inherited_envs` configurable (as suggested [here](https://github.com/jupyter-server/enterprise_gateway/pull/1225#issuecomment-1357919983)), this change updates the start script of the `enterprise-gateway-demo` image to add the value of env `PYSPARK_PYTHON` via `inherited_envs` since that's the minimal value necessary to get the `TestRKernelClient` test passing.  It also serves as an example of how to propagate a value from the EG process to kernels.

Start EG in demo-image to inherit PYSPARK_PYTHON env

---

enterprise_gateway/itests/test_python_kernel.py

The python interrupt tests (for all integrations on Yarn) started failing due to string length limits because it was building a string whose length got too long.  Not sure why this just started failing CI but there must have been some kind of update to check that.  This pull request makes the python interrupts more like the Scala and R interrupt tests where a `sleep()` call is getting interrupted.  
(Note that the building of the long string was to generate CPU load for the [PR at the time](https://github.com/jupyter-server/enterprise_gateway/pull/686), which switched the launcher from a thread to a process since a kernel's operation could starve the ability for the thread to perform the interrupt.  Given that we've demonstrated that, I feel it's okay to make these tests like the other …

Update python interrupt test

---

docs/source/operators/deploy-kubernetes.md
etc/kernel-launchers/operators/scripts/launch_custom_resource.py
etc/kernel-launchers/operators/scripts/sparkoperator.k8s.io-v1beta2.yaml.j2

This pull request applies similar logic for flowing envs to spark-operator pods to that used by regular pods.  The envs are added into the container's specification if the CRD's resource group is `sparkoperator.k8s.io`.  Both the _driver_ and _executor_ envs are updated.  If the group is not `sparkoperator.k8s.io`, nothing occurs since, presumably, the location of the env stanza will be different.
While troubleshooting this change, it was discovered that the spark operator's `webhook server` must be enabled for envs to be transferred.  As a result, both the deployment document and the spark application jinja template have been updated with the appropriate `helm` command.
Since the doc update uses a nested Note/Tip box that looks a bit strange in the raw text, I'm including a screenshot …

Flow envs to spark operator pods

---

etc/docker/kernel-py/Dockerfile
etc/docker/kernel-r/Dockerfile
etc/docker/kernel-tf-py/Dockerfile

This pull request _preemptively_ disables the `HEALTHCHECK` command that _may be_ inherited from the [jupyter/docker-stacks](https://github.com/jupyter/docker-stacks) images.  Note that the inherited notebook images do not currently have `HEALTHCHECK` commands as they were added in March of 2022 and we currently base images from January of 2022, but I wanted to get these updates in place in case the base images are updated (thus the italics).
I've confirmed the images are operational (in Kubernetes) and exhibit the expected metadata produced via `docker inspect`:
```json
"Healthcheck": {
"Test": [
"NONE"
]
},
```
Resolves #1218

Disable healthcheck on kernel-images derived from notebook images

---

etc/docker/demo-base/Dockerfile
etc/docker/kernel-spark-py/Dockerfile
etc/docker/kernel-spark-r/Dockerfile

When building the images for the 3.2.0 release, the multiarch build was hanging and you could see in the image build logs that they were trying to download/install java and never completing those. Google came to the rescue and suggested updating java certs which resolved the issues. 
```
=> [linux/amd64  2/28] RUN dpkg --purge --force-depends ca-certificates-java     && apt-get update && apt-get -yq dist-upgrade     && apt-get install -yq --no-install-recommen  20118.7s
=> => # Setting up libfontconfig1:amd64 (2.13.1-4.2) ...                                                                                                                                 
=> => # Setting up libavahi-client3:amd64 (0.8-5+deb11u1) ... …
```

Update java certs to avoid multi-arch builds to hang

---

etc/kernel-launchers/kubernetes/scripts/launch_kubernetes.py
etc/kernel-launchers/operators/scripts/launch_custom_resource.py

A submitted kernel can fail due to the malformation of 
YAML/CRD contents and in this case, dumping the 
files in the log can help with problem determination.

Dump Kubernetes YAML/CRD on kernel startup fails

---

enterprise_gateway/client/gateway_client.py
enterprise_gateway/itests/test_authorization.py
enterprise_gateway/itests/test_python_kernel.py
enterprise_gateway/itests/test_r_kernel.py
enterprise_gateway/itests/test_scala_kernel.py

I made a few small changes to the gateway client locally that I wanted to contribute back. One big issue I dealt with was with my connection to the websocket and http api endpoints failing, so I think it would be really helpful if in the code there was somehow an indication to use secure endpoints. Additionally, we found that we needed to pass a lot of environment variables, so an extra_env dictionary is helpful if you're calling the gateway client and need to pass, for example, queue-specific environment variables. Additionally, in kernel.execute, we should somehow let whatever's calling that function know whether an error was returned or not. As it stands now, kernel.execute will take an error and convert it to text - but what if for example, we're testing some notebook code - to do …

A few small changes to gateway client

---

etc/kernel-launchers/bootstrap/bootstrap-kernel.sh

This pull request fixes an issue with the value and the assignment syntax being used to populate the `kernel_class_option` variable inside the `bootstrap-kernel.sh` script. This will resolve the flow of `--kernel-class-name` option from the bootstrap script to python kernel launcher in the kernel containers.
Please find more details on the issue [here](https://github.com/jupyter-server/enterprise_gateway/pull/1187#discussion_r1115799809).
Resolves [#1184](https://github.com/jupyter-server/enterprise_gateway/issues/1184)

Fix the flow of kernel-class-name option in bootstrap script

---

docs/source/conf.py
docs/source/contributors/devinstall.md

This pull request addresses some docs issues that just came up.
1. An updated version of Sphinx wants a language to be set, so we set the language to `'en'`.
2. The conda docs page for managing environments is no longer working (perhaps temporary) for `latest`, so this changes it to `stable` - where the page can be found.

Set language and fix conda env link

---

enterprise_gateway/client/gateway_client.py
enterprise_gateway/itests/test_authorization.py
enterprise_gateway/services/kernels/remotemanager.py

Enhance the remove_kernel to properly handle not found kernels (key error) to better support duplicate restarts or restart/shutdown use cases. 
Fixes #1261

Handle not found exception during remove_kernel

---

Makefile

The version string update code used when creating releases happened to think the `3.2.1` value for `SPARK_VERSION` was the EG release value when, instead, we treat that value as a fixed value.  This value also happens to be the tag for the `elyra/demo-base` docker image - which is the base image for the `elyra/enterprise-gateway-demo` image used to run the integration tests.  Because SPARK_VERSION was no longer reflecting `3.2.1` (but `3.3.0.dev0`) the enterprise-gateway-demo image could not be built - resulting in build failures.  This PR resets the value back to `3.2.1`.
Since we should only have one `3.2.1` release, I don't see this issue being a problem again, so am not bothering to "fix" the release script to avoid its update.

Reset SPARK_VERSION to 3.2.1

---

etc/kernel-launchers/kubernetes/scripts/kernel-pod.yaml.j2
etc/kernel-launchers/operators/scripts/sparkoperator.k8s.io-v1beta2.yaml.j2

While reviewing some of the spark operator artifacts 
I noticed it was not setting the Kubernetes 
restart policy to never as the other kernelspecs

Set restart strategy to never for spark operator

---

enterprise_gateway/services/processproxies/docker_swarm.py

Since this [commit](https://github.com/jupyter-server/enterprise_gateway/commit/56dffccb7740dd0eeea115cfe7f4233599b6bc1e), starting kernel-py containers via dockerswarm proxy will eventually fail because when get_error_states is reached, NotImplementedError is raise, thus causing a disruption in the scheduling logic
This fix urges to improve that, by specifying error states, taken from https://docs.docker.com/engine/swarm/how-swarm-mode-works/swarm-task-states/

Fix docker swarm not being to start due to missing inherited function on the latest version

---

etc/docker/enterprise-gateway/Dockerfile
etc/docker/kernel-py/Dockerfile
etc/docker/kernel-r/Dockerfile
etc/docker/kernel-tf-py/Dockerfile

This PR includes changes to Update the tag of the base image used in the following docker files to the latest available tag.
- kernel-py
- kernel-r
- kernel-tf-py
- enterprise-gateway
Existing tag: 2022-01-24
Updated tag: 2023-03-13
- The existing base image with tag 2022-01-24 was built a year ago with the ubuntu:22.04 as base image built back then. Over time several security vulnerabilities and bugs were fixed and there would be some performance improvements in the ubuntu:22.04 docker image. Updating the base image to the 2023-03-13 tag which in turn uses the latest available ubuntu:22.04 ensures that the latest security patches are applied to the kernel, reducing the risk of potential security issues and taking advantage of improved performance.
- Over time, new versions of …

Updating base image tag to latest available tag

---

enterprise_gateway/client/gateway_client.py

The heart of the code that shuts down the kernel (the API request) should be within `KernelClient` itself. This way, when the kernel can shut itself done without the help of `GatewayClient`. This is important in handling the websocket exception, as when we call `kernel.shutdown()`, we actually want to run the API request to shut down the kernel as well. 
Additionally, we should still raise the exception on `KernelClient.__init__()` if the websocket connection fails, as that way `GatewayClient.start_kernel` will error out if the connection to the `KernelClient` isn't working.

Move shutdown kernel code to be within KernelClient

---

enterprise_gateway/services/processproxies/yarn.py

Currently, Jupyter Server only supports "REQUIRED" mutual authentication on YARN, which may not be sufficient for some use cases. For example, in scenarios where mutual authentication is not required to establish a secure connection between the server and clients, there is no built-in way to configure this in Enterprise Gateway.
I suggest adding an option to the Jupyter Server configuration that allows users optional mutual authentication. When introducing this feature, users can specify with REQUIRED, OPTIONAL or DISABLED. This enhancement would greatly improve user configuration freedom.
I included a variable `EG_YARN_MUTUAL_AUTHENTICATION` which users can specify with REQUIRED, OPTIONAL or DISABLED. The value is REQUIRED by defaul

feat: Add options to mutual authentication

---

README.md

The old list was very weird, sometimes it used "_" and sometimes it used "*", which confused me. So I created this PR

docs: reformat list

---

etc/kubernetes/helm/enterprise-gateway/templates/deployment.yaml

This enables successful usage of deployment nodeselectors, tolerations, and affinity. These were previously disabled due to a scoping issue.

[Bug] Fix helm chart logic error

---

etc/docker/kernel-image-puller/Dockerfile

relate: https://github.com/jupyter-server/enterprise_gateway/issues/1363
This is **Independently upgrade cri-tools to v1.24.0 or higher** solution.
> I am trying to pull from a private registry using the CRICTL_AUTH environment variable. However, this feature is only available in crictl (cri-tools) versions v1.24.0 and above.
Currently, I am using v1.21.0 which is related to the OS version.

update crictl version from v1.21.0 to v1.24.0

---

.github/workflows/build.yml
etc/docker/demo-base/Dockerfile
etc/docker/kernel-tf-py/Dockerfile
pyproject.toml

Docker fixes:
- Update Debian security repository for the demo-base docker image
- Use more recent TensorFlow base image as old one is unavailable
Fixes #1371

Docker fixes

---

enterprise_gateway/services/kernels/handlers.py

* **Description:** When Kubernetes is in replication availability mode, deleting the kernel or creating a WebSocket connection may cause a 404 error due to unsynchronized sessions.
* **Related issue:** #1373

Check kernel id before delete and upgrade ws

---

Makefile
enterprise_gateway/services/processproxies/k8s.py

This change fix - Error: module 'kubernetes.client' has no attribute 'V1Subject'
This error occurs when an attempt is made to create a role binding.
The full error looks as follows:
```
[E 2024-06-03 08:58:36.252 EnterpriseGatewayApp] Error occurred creating role binding for namespace 'jovyan-153ca7c1-c68f-440d-b678-f8926b48afbc': module 'kubernetes.client' has no attribute 'V1Subject'
```

change V1Subject to RbacV1Subject in k8s.py
